Repository NVIDIA/TransformerEngine, pull requests merged in 2023-07, with the labels that each got.

#307 Check for cuDNN frontend API when building
  transformer_engine/common/CMakeLists.txt
Labels: enhancement

#315 Stop creating pip wheels in GitHub build tests
  .github/workflows/build.yml
Labels: bug

#312 Disable TorchDynamo optimizations in PyTorch modules
  qa/L0_unittest/test.sh
  tests/pytorch/test_jit.py
  transformer_engine/pytorch/jit.py
  transformer_engine/pytorch/module/layernorm.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: bug

#324 [JAX] Fully remove attn_type and set self_attn_mask_type default to 'causal'
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
  examples/jax/encoder/test_multiprocessing_encoder.py
  examples/jax/encoder/test_single_gpu_encoder.py
  tests/jax/test_layer.py
  tests/jax/test_praxis_layers.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/praxis/transformer.py
Labels: v0.11.0

#329 FlashAttention 2.0 support
  setup.py
  transformer_engine/pytorch/attention.py
Labels: v0.11.0

#331 Relax FA 2.0 checks for Ada
  transformer_engine/pytorch/attention.py
Labels: v0.11.0

#332 Replace deprecated sharding API in JAX test
  tests/jax/test_sharding.py
Labels: bug

#339 Make QK layer scaling opt-in
  transformer_engine/pytorch/attention.py
Labels: v0.11.0

#306 Exposing RMSNorm in pyTorch
  docs/api/c/index.rst
  docs/api/c/rmsnorm.rst
  docs/api/pytorch.rst
  setup.py
  tests/pytorch/test_numerics.py
  tests/pytorch/test_onnx_export.py
  tests/pytorch/test_sanity.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/cpp_extensions/normalization.py
  transformer_engine/pytorch/csrc/common.cu
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.cu
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/activation.cu
  transformer_engine/pytorch/csrc/extensions/attention.cu
  transformer_engine/pytorch/csrc/extensions/cast.cu
  transformer_engine/pytorch/csrc/extensions/gemm.cu
  transformer_engine/pytorch/csrc/extensions/misc.cu
  transformer_engine/pytorch/csrc/extensions/normalization.cu
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/extensions/softmax.cu
  transformer_engine/pytorch/csrc/extensions/transpose.cu
  transformer_engine/pytorch/csrc/ts_fp8_op.cpp
  transformer_engine/pytorch/module/__init__.py
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/rmsnorm.py
  transformer_engine/pytorch/te_onnx_extensions.py
  transformer_engine/pytorch/transformer.py
Labels: v0.11.0

#343 [PyTorch] Minor bug fix
  transformer_engine/pytorch/module/layernorm_mlp.py
Labels: bug

#338 Add support for multi-query and grouped-query attention
  qa/L0_unittest/test.sh
  setup.py
  tests/pytorch/test_fused_attn.py
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/transformer.py
Labels: v0.11.0

#346 Add compilation OOM note for FA 2.0
  README.rst
Labels: v0.11.0
