Repository NVIDIA/TransformerEngine, pull requests merged in 2023-10, with the labels that each got.

#449 Atomic gemm and FP8 Reduce Scatter
  tests/pytorch/test_onnx_export.py
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/common/include/transformer_engine/gemm.h
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/cpp_extensions/gemm.py
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/gemm.cu
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.h
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/transformer.py
Labels: 0.13.0

#444 [JAX] Enhance Dropout in TransformerLayer.
  tests/jax/test_helper.py
  tests/jax/test_layer.py
  tests/jax/test_praxis_layers.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/fp8.py
  transformer_engine/jax/praxis/transformer.py
Labels: bug, 0.13.0

#463 Update reference scale calculation in TensorFlow test
  tests/tensorflow/test_layers.py
Labels: bug

#462 Disable GitHub CI jobs using NGC PyTorch container
  .github/workflows/build.yml
  .github/workflows/lint.yml
Labels: bug

#397 Debug CI tests on Ada
  tests/jax/test_custom_call_compute.py
  tests/jax/test_fused_attn.py
  tests/paddle/test_layers.py
  tests/paddle/test_operators.py
  tests/paddle/utils.py
  tests/pytorch/test_fused_attn.py
  transformer_engine/paddle/layer/attention.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/fp8.py
  transformer_engine/pytorch/utils.py
Labels: bug

#474 Remove remaining references to TensorFlow
  .github/workflows/build.yml
  .github/workflows/lint.yml
  README.rst
  setup.py
Labels: documentation, testing

#476 Explicitly specify that PyTorch QA tests use PyTorch
  .github/workflows/lint.yml
  CONTRIBUTING.rst
  qa/L0_pytorch_lint/CPPLINT.cfg
  qa/L0_pytorch_lint/format_py_files.sh
  qa/L0_pytorch_lint/pylintrc
  qa/L0_pytorch_lint/test.sh
  qa/L0_pytorch_unittest/test.sh
Labels: testing

#484 [PyTorch] rm unused docs
  docs/api/pytorch.rst
Labels: 1.0.0

#483 Fix incorrect dtype in LayerNormLinear
  transformer_engine/pytorch/module/layernorm_linear.py
Labels: bug

#480 [JAX] Canonicalize the dtype for the better user experience
  transformer_engine/jax/cpp_extensions.py
Labels: enhancement

#487 [PyTorch] Fixes and tests for FP8 + activation recompute
  tests/pytorch/test_fused_attn.py
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/fp8.py
  transformer_engine/pytorch/module/base.py
Labels: 1.0.0

#479 Fix CMakeList.txt to build as a sub-project
  transformer_engine/CMakeLists.txt
  transformer_engine/common/CMakeLists.txt
Labels: bug

#382 Refactor logging macros
  setup.py
  tests/cpp/operator/test_cast_transpose.cu
  tests/cpp/operator/test_cast_transpose_dbias.cu
  tests/cpp/operator/test_cast_transpose_dbias_dgelu.cu
  tests/cpp/operator/test_cast_transpose_dgeglu.cu
  tests/cpp/operator/test_dgeglu.cu
  tests/cpp/operator/test_geglu.cu
  tests/cpp/operator/test_gelu.cu
  tests/cpp/operator/test_layernorm.cu
  tests/cpp/operator/test_multi_cast_transpose.cu
  tests/cpp/operator/test_qdq.cu
  tests/cpp/operator/test_rmsnorm.cu
  tests/cpp/operator/test_transpose.cu
  tests/cpp/test_common.cu
  tests/cpp/test_common.h
  transformer_engine/common/common.h
  transformer_engine/common/fused_softmax/scaled_masked_softmax.cu
  transformer_engine/common/fused_softmax/scaled_upper_triang_masked_softmax.cu
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/common/include/transformer_engine/logging.h
  transformer_engine/common/include/transformer_engine/transpose.h
  transformer_engine/common/util/cuda_driver.h
  transformer_engine/common/util/logging.h
  transformer_engine/jax/csrc/modules.h
  transformer_engine/jax/csrc/utils.h
  transformer_engine/paddle/csrc/common.h
  transformer_engine/paddle/csrc/custom_ops.cu
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
Labels: bug, enhancement

#489 [paddle] add documentation
  docs/api/framework.rst
  docs/api/paddle.rst
  transformer_engine/paddle/fp8.py
  transformer_engine/paddle/layer/attention.py
  transformer_engine/paddle/layer/layernorm.py
  transformer_engine/paddle/layer/layernorm_linear.py
  transformer_engine/paddle/layer/layernorm_mlp.py
  transformer_engine/paddle/layer/linear.py
  transformer_engine/paddle/layer/softmax.py
  transformer_engine/paddle/layer/transformer.py
  transformer_engine/paddle/recompute.py
Labels: 1.0.0

#452 [PyTorch] Experimental FP8 tensor class
  docs/api/pytorch.rst
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/test_float8tensor.py
  tests/pytorch/test_numerics.py
  tests/pytorch/test_onnx_export.py
  tests/pytorch/test_torch_save_load.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/float8_tensor.py
  transformer_engine/pytorch/fp8.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: enhancement, 1.0.0
