Repository NVIDIA/TransformerEngine, pull requests merged in 2023-05, with the labels that each got.

#185 Move dbias from fused attention bwd's input list to its output list
  transformer_engine/common/fused_attn/fused_attn.cpp
  transformer_engine/common/include/transformer_engine/fused_attn.h
  transformer_engine/pytorch/cpp_extensions.py
  transformer_engine/pytorch/csrc/extensions.cu
  transformer_engine/pytorch/csrc/extensions.h
Labels: 0.8.0

#204 Add instructions in cuDNN error message for cuDNN error logging
  transformer_engine/common/include/transformer_engine/logging.h
Labels: enhancement

#138 Support for NVRTC kernels
  docs/installation.rst
  tests/cpp/CMakeLists.txt
  tests/cpp/operator/test_transpose.cu
  tests/cpp/util/CMakeLists.txt
  tests/cpp/util/test_nvrtc.cpp
  tests/cpp/util/test_string.cpp
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/common.h
  transformer_engine/common/include/transformer_engine/logging.h
  transformer_engine/common/transpose/rtc/transpose.cu
  transformer_engine/common/transpose/transpose.cu
  transformer_engine/common/util/cuda_driver.cpp
  transformer_engine/common/util/cuda_driver.h
  transformer_engine/common/util/cuda_runtime.cpp
  transformer_engine/common/util/cuda_runtime.h
  transformer_engine/common/util/rtc.cpp
  transformer_engine/common/util/rtc.h
  transformer_engine/common/util/string.h
  transformer_engine/common/util/string_header.h.in
  transformer_engine/common/util/system.cpp
  transformer_engine/common/util/system.h
  transformer_engine/common/utils.cuh
Labels: enhancement

#226 Relax checks for attn_mask_type in FlashAttention
  transformer_engine/pytorch/attention.py
Labels: 0.9.0

#236 Jax bug fixes for the dot product attention
  tests/jax/test_fused_attn.py
  tests/jax/test_layer.py
  transformer_engine/common/fused_attn/fused_attn_fp16_bf16_max_seqlen_512.cu
  transformer_engine/common/fused_attn/fused_attn_fp8.cu
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/sharding.py
Labels: bug, 0.9.0
