Repository NVIDIA/TransformerEngine, pull requests merged in 2023-04, with the labels that each got.

#129 Add FP8 support for Ada
  tests/pytorch/test_onnx_export.py
  tests/pytorch/test_sanity.py
  transformer_engine/CMakeLists.txt
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.cu
  transformer_engine/pytorch/fp8.py
Labels: v0.7.0

#104 GitHub actions for JAX and TensorFlow
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/license.yml
  .github/workflows/lint.yml
  tests/jax/test_sanity_import.py
Labels: enhancement

#130 make bias configurable
  setup.py
  tests/pytorch/test_sanity.py
  transformer_engine/common/rmsnorm/rmsnorm_api.cpp
  transformer_engine/pytorch/jit.py
  transformer_engine/pytorch/module.py
  transformer_engine/pytorch/transformer.py
Labels: enhancement

#153 Tighten tolerances for graph capture test
  tests/pytorch/test_numerics.py
Labels: bug

#157 Simplify dev installation guide.
  README.rst
Labels: documentation

#147 TP communication overlap with userbuffers
  qa/L0_cppunittest/test.sh
  qa/L0_jax_lint/CPPLINT.cfg
  qa/L0_lint/CPPLINT.cfg
  qa/L0_tensorflow_lint/CPPLINT.cfg
  setup.py
  tests/cpp/CMakeLists.txt
  tests/cpp/operator/CMakeLists.txt
  transformer_engine/__init__.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/__init__.py
  transformer_engine/common/comm_gemm_overlap/userbuffers-host.cpp
  transformer_engine/common/comm_gemm_overlap/userbuffers.cu
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/common/include/transformer_engine/gemm.h
  transformer_engine/common/include/transformer_engine/userbuffers.h
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/pytorch/cpp_extensions.py
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/extensions.cu
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/ts_fp8_op.cpp
  transformer_engine/pytorch/module.py
  transformer_engine/pytorch/transformer.py
  transformer_engine/tensorflow/csrc/extensions.cu
Labels: 0.8.0

#162 Move userbuffer to PyTorch
  qa/L0_cppunittest/test.sh
  setup.py
  tests/cpp/CMakeLists.txt
  tests/cpp/operator/CMakeLists.txt
  transformer_engine/CMakeLists.txt
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/__init__.py
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/extensions.cu
  transformer_engine/pytorch/csrc/userbuffers/CMakeLists.txt
  transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.h
Labels: 0.8.0

#163 zero inter-node communication buffer
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.h
Labels: 0.8.0

#164 Remove userbuf docs
  transformer_engine/pytorch/transformer.py
Labels: 0.8.0

#181 Remove the nonexistent parameter from fused attention documentation
  transformer_engine/common/include/transformer_engine/fused_attn.h
Labels: 0.8.0

#180 Re-add support for PyTorch version 1.x
  transformer_engine/pytorch/transformer.py
Labels: 0.8.0

#169 [JAX] Adjust Module Structure.
  README.rst
  docs/api/jax.rst
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
  examples/jax/encoder/test_single_gpu_encoder.py
  examples/jax/mnist/test_single_gpu_mnist.py
  tests/jax/test_layer.py
  tests/jax/test_sharding.py
  transformer_engine/common/utils.py
  transformer_engine/jax/__init__.py
  transformer_engine/jax/flax/__init__.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/flax/transformer.py
Labels: enhancement, 0.8.0

#178 Bugfix in Sequence Parallelism
  transformer_engine/pytorch/module.py
Labels: bug

#184 Correct cuDNN version requirement
  docs/installation.rst
Labels: 0.8.0
