Repository NVIDIA/TransformerEngine, pull requests merged in 2023-03, with the labels that each got.

#101 Use 4B vector loads/stores in cast-transpose kernel for small matrices
  transformer_engine/common/transpose/cast_transpose.cu
Labels: enhancement

#113 Catch FA internal error with compute capability 8.6
  transformer_engine/pytorch/transformer.py
Labels: v0.7.0

#114 Fix usage of return_bias argument
  transformer_engine/pytorch/module.py
  transformer_engine/pytorch/transformer.py
Labels: v0.7.0

#121 Fix zombie process when querying TE install path
  transformer_engine/common/__init__.py
  transformer_engine/pytorch/transformer.py
Labels: bug

#108 [JAX] Add TE examples
  examples/jax/README.md
  examples/jax/encoder/README.md
  examples/jax/encoder/requirements.txt
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
  examples/jax/encoder/test_single_gpu_bf16_training.py
  examples/jax/encoder/test_single_gpu_encoder.py
  examples/jax/encoder/test_single_gpu_fp8_training.py
  examples/jax/mnist/README.md
  examples/jax/mnist/requirements.txt
  examples/jax/mnist/test_single_gpu_mnist.py
  qa/L0_jax_unittest/test.sh
  qa/L0_license/config.json
  qa/L0_license/copyright_checker.py
  tests/jax/test_mnist.py
  transformer_engine/jax/module.py
  transformer_engine/jax/transformer.py
Labels: v0.7.0

#119 Fix Bugs of TE/JAX
  tests/jax/test_sharding.py
  tests/jax/utils.py
  transformer_engine/jax/fp8.py
  transformer_engine/jax/module.py
  transformer_engine/jax/transformer.py
Labels: bug, v0.7.0

#112 Change FP8 recipe defaults
  tests/pytorch/test_onnx_export.py
  transformer_engine/common/recipe.py
  transformer_engine/pytorch/module.py
Labels: v0.7.0

#126 Fix segfault during onnx export
  transformer_engine/pytorch/te_onnx_extensions.py
Labels: v0.7.0
