Repository NVIDIA/TransformerEngine, pull requests merged in 2023-11, with the labels that each got.

#505 [JAX] Bugfix for insufficient GPUs crash in distributed ops
  tests/jax/distributed_configs_helper.py
  tests/jax/distributed_ops_helper.py
  tests/jax/test_distributed_custom_ops.py
Labels: bug

#508 [PyTorch] Disable large test cases for Transformer layer
  tests/pytorch/test_fused_attn.py
Labels: bug

#501 [JAX] Use FP8 tolerances in FP8 tests
  examples/jax/mnist/test_single_gpu_mnist.py
  tests/jax/test_custom_call_compute.py
  tests/jax/utils.py
Labels: testing

#472 [JAX] Migrating from Xmap to Custom Partitioning for All Custom Calls
  README.rst
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
  examples/jax/encoder/test_multiprocessing_encoder.py
  examples/jax/encoder/test_single_gpu_encoder.py
  examples/jax/mnist/test_single_gpu_mnist.py
  tests/jax/distributed_configs_helper.py
  tests/jax/distributed_ops_helper.py
  tests/jax/distributed_test_base.py
  tests/jax/test_custom_call_compute.py
  tests/jax/test_custom_call_shape.py
  tests/jax/test_distributed_custom_ops.py
  tests/jax/test_distributed_fused_attn.py
  tests/jax/test_distributed_layernorm.py
  tests/jax/test_distributed_softmax.py
  tests/jax/test_helper.py
  tests/jax/test_sharding.py
  tests/jax/utils.py
  transformer_engine/jax/__init__.py
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/dot.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/fp8.py
  transformer_engine/jax/fused_attn.py
  transformer_engine/jax/layernorm.py
  transformer_engine/jax/mlp.py
  transformer_engine/jax/praxis/module.py
  transformer_engine/jax/sharding.py
  transformer_engine/jax/softmax.py
Labels: enhancement

#540 Use unsigned char when instantiating DType::kByte
  transformer_engine/common/common.h
Labels: bug

#523 [JAX] Use relative idx to ScaledUpperTriangMaskedSoftmaxFwdPrimitive
  transformer_engine/jax/cpp_extensions.py
Labels: bug
