Repository NVIDIA/TransformerEngine, pull requests merged in 2024-04, with the labels that each got.

#734 Set CUDA context before loading NVRTC kernels
  transformer_engine/common/util/rtc.cpp
Labels: bug

#721 Add NVLS-MC based UB kernels
  transformer_engine/pytorch/csrc/userbuffers/CMakeLists.txt
  transformer_engine/pytorch/csrc/userbuffers/ipcsocket.cc
  transformer_engine/pytorch/csrc/userbuffers/ipcsocket.h
  transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu
Labels: 1.6.0

#739 Do not store input activations when not computing weight gradients
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
Labels: 1.6.0

#732 Atomic gemm for TP-AR and TP-RS overlap with P2P exchanges
  transformer_engine/pytorch/cpp_extensions/gemm.py
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.h
  transformer_engine/pytorch/module/base.py
Labels: 1.6.0

#748 [PyTorch] Fix backward compatibility for checkpoint API
  transformer_engine/pytorch/distributed.py
Labels: 1.5.0

#747 Compile tuned RMSNorm kernels for hidden size 8192
  transformer_engine/common/rmsnorm/rmsnorm_bwd_semi_cuda_kernel.cu
  transformer_engine/common/rmsnorm/rmsnorm_fwd_cuda_kernel.cu
Labels: enhancement

#755 Fix the default userbuffer communicator init settings
  transformer_engine/pytorch/module/base.py
Labels: 1.6.0

#744 [JAX] Adapt latest JAX/PAX image
  tests/jax/test_custom_call_compute.py
  tests/jax/utils.py
Labels: jax

#763 Fix undefined symbol issue for transformer_engine::getenv
  setup.py
Labels: 1.6.0

#575 [PyTorch] cuda graph support
  docs/api/pytorch.rst
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/test_cuda_graphs.py
  tests/pytorch/test_float8tensor.py
  tests/pytorch/test_numerics.py
  tests/pytorch/test_onnx_export.py
  tests/pytorch/test_sanity.py
  transformer_engine/common/include/transformer_engine/cast_transpose_noop.h
  transformer_engine/common/include/transformer_engine/recipe.h
  transformer_engine/common/layer_norm/ln_api.cpp
  transformer_engine/common/recipe/__init__.py
  transformer_engine/common/recipe/delayed_scaling.cu
  transformer_engine/common/rmsnorm/rmsnorm_api.cpp
  transformer_engine/common/transpose/cast_transpose.cu
  transformer_engine/common/transpose/rtc/transpose.cu
  transformer_engine/common/transpose/transpose.cu
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/cpp_extensions/transpose.py
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/extensions/recipe.cu
  transformer_engine/pytorch/csrc/extensions/transpose.cu
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/float8_tensor.py
  transformer_engine/pytorch/fp8.py
  transformer_engine/pytorch/graph.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/transformer.py
Labels: 1.6.0

#775 [PyTorch] Fix kernel_bulk launch config
  transformer_engine/common/recipe/delayed_scaling.cu
Labels: bug, 1.6.0

#772 Add SM margin to LayerNorm in inference
  tests/pytorch/test_onnx_export.py
  transformer_engine/paddle/layer/layernorm_linear.py
  transformer_engine/paddle/layer/layernorm_mlp.py
  transformer_engine/pytorch/cpp_extensions/normalization.py
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/normalization.cu
  transformer_engine/pytorch/csrc/ts_fp8_op.cpp
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/layernorm.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/rmsnorm.py
  transformer_engine/pytorch/te_onnx_extensions.py
Labels: 1.6.0

#783 [PyTorch] Use __torch_function__ as a class method
  transformer_engine/pytorch/float8_tensor.py
Labels: 1.6.0

#782 [PyTorch] TE checkpoint pass-through logic fix
  transformer_engine/pytorch/distributed.py
Labels: bug

#784 [PyTorch] Misc fixes for release_v1.6
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/utils.py
Labels: 1.6.0

#790 [PyTorch] Fix for type checking failure on custom callables
  transformer_engine/pytorch/distributed.py
Labels: bug

#785 [JAX] Fixing CI failure due to incorrect use of `static_argnums` in jax.jit
  examples/jax/encoder/test_single_gpu_encoder.py
  examples/jax/mnist/test_single_gpu_mnist.py
  qa/L0_jax_unittest/test.sh
  qa/L1_jax_distributed_unittest/test.sh
  tests/jax/pytest.ini
Labels: bug, jax

#258 NVRTC kernels for cast-transpose
  tests/cpp/operator/test_cast_transpose.cu
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/transpose/cast_transpose.cu
  transformer_engine/common/transpose/rtc/cast_transpose.cu
  transformer_engine/common/transpose/transpose.cu
Labels: enhancement

#719 [PyTorch] Stop storing fused weight tensor in linear modules
  tests/pytorch/test_numerics.py
  tests/pytorch/test_sanity.py
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/linear.py
Labels: bug, enhancement, testing

#780 [JAX] Allow multi-dims for dgamma and dbeta in LN descriptor.
  examples/jax/encoder/test_single_gpu_encoder.py
  examples/jax/mnist/test_single_gpu_mnist.py
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/jax/csrc/modules.h
Labels: enhancement, jax

#795 [PyTorch] Fix typo from #768
  transformer_engine/pytorch/module/base.py
Labels: bug

#794 [PyTorch] Remove unnecessary Pylint overrides
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/cpu_offload.py
  transformer_engine/pytorch/float8_tensor.py
  transformer_engine/pytorch/fp8.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/softmax.py
Labels: bug, 1.6.0

#765 [JAX] Unifying GeLU and GeGLU in LayerNorm MLP
  tests/jax/test_custom_call_compute.py
  transformer_engine/common/transpose/cast_transpose_fusion.cu
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/csrc/extensions.cpp
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/jax/csrc/modules.h
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/mlp.py
Labels: enhancement, jax

#798 [PyTorch] Avoid using LRU cache for cu_seqlens
  transformer_engine/pytorch/attention.py
Labels: 1.6.0

#773 [JAX] SwiGLU Implementation
  tests/jax/test_custom_call_compute.py
  tests/jax/test_layer.py
  tests/jax/test_praxis_layers.py
  transformer_engine/common/activation/activation_template.h
  transformer_engine/common/activation/gelu.cu
  transformer_engine/common/activation/relu.cu
  transformer_engine/common/activation/swiglu.cu
  transformer_engine/common/include/transformer_engine/activation.h
  transformer_engine/common/include/transformer_engine/transpose.h
  transformer_engine/common/transpose/cast_transpose_fusion.cu
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/csrc/extensions.cpp
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/jax/csrc/modules.h
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/mlp.py
Labels: enhancement, jax

#813 Add module level filter for deprecation warning in common
  transformer_engine/common/utils.py
Labels: enhancement

#819 [PyTorch] Fix tp_group_initialized error
  transformer_engine/pytorch/attention.py
Labels: 1.6.0

#816 [PyTorch] Fix linter warnings from unused args
  .gitignore
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/float8_tensor.py
Labels: bug

#825 Avoid amax roll for non-run modules
  transformer_engine/common/recipe/delayed_scaling.cu
Labels: 1.6.0
