Repository NVIDIA/TransformerEngine, pull requests merged in 2024-06, with the labels that each got.

#830 Added comments about Llama3 weights to Llama tutorial
  docs/examples/te_llama/te_llama.py
  docs/examples/te_llama/tutorial_accelerate_hf_llama_with_te.ipynb
  docs/examples/te_llama/utils.py
Labels: documentation, 1.7.0

#869 [PyTorch] Add CUDA graph tests with FP8 weight caching
  tests/pytorch/test_cuda_graphs.py
  transformer_engine/pytorch/graph.py
Labels: bug

#893 [PaddlePaddle] Fix editable build for paddle
  build_tools/build_ext.py
Labels: build

#898 Fix minor security vulnerability when triggering CI
  .github/workflows/blossom-ci.yml
  .github/workflows/trigger-ci.yml
Labels: bug

#865 [PyTorch] Avoid select op in PyTorch extensions
  transformer_engine/pytorch/cpp_extensions/normalization.py
  transformer_engine/pytorch/cpp_extensions/transpose.py
  transformer_engine/pytorch/csrc/common.cu
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/normalization.cu
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/extensions/transpose.cu
  transformer_engine/pytorch/csrc/ts_fp8_op.cpp
Labels: enhancement

#902 [JAX] Made order of gated act consistent in all branches
  transformer_engine/jax/flax/module.py
Labels: bug, jax

#912 Value initialize packing descriptors
  transformer_engine/jax/csrc/extensions/packing.cpp
Labels: bug

#911 Fix local cpp tests after inplace build
  tests/cpp/CMakeLists.txt
Labels: bug

#903 [Common] Added JIT-compiled fused cast transpose kernels
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/transpose/cast_transpose_fusion.cu
  transformer_engine/common/transpose/rtc/cast_transpose_fusion.cu
  transformer_engine/common/util/rtc.cpp
  transformer_engine/common/util/rtc.h
  transformer_engine/common/utils.cuh
Labels: enhancement

#899 [JAX] Splitting cpp_extensions.py
  tests/jax/test_custom_call_compute.py
  tests/jax/test_distributed_fused_attn.py
  tests/jax/test_distributed_layernorm_mlp.py
  tests/jax/test_fused_attn.py
  tests/jax/test_softmax.py
  transformer_engine/jax/attention.py
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/cpp_extensions/__init__.py
  transformer_engine/jax/cpp_extensions/activation.py
  transformer_engine/jax/cpp_extensions/attention.py
  transformer_engine/jax/cpp_extensions/base.py
  transformer_engine/jax/cpp_extensions/custom_call.py
  transformer_engine/jax/cpp_extensions/misc.py
  transformer_engine/jax/cpp_extensions/normalization.py
  transformer_engine/jax/cpp_extensions/quantization.py
  transformer_engine/jax/cpp_extensions/softmax.py
  transformer_engine/jax/cpp_extensions/transpose.py
  transformer_engine/jax/dot.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/layernorm.py
  transformer_engine/jax/layernorm_mlp.py
  transformer_engine/jax/praxis/transformer.py
  transformer_engine/jax/softmax.py
Labels: enhancement, jax

#886 Use unoptimized RMSNorm kernel if pointers are not aligned
  transformer_engine/common/rmsnorm/rmsnorm_api.cpp
Labels: bug

#931 [Common] Remove CheckTensor if the workspace is empty in cast_transpose_fused
  examples/jax/mnist/test_single_gpu_mnist.py
  transformer_engine/common/transpose/cast_transpose_fusion.cu
Labels: bug

#932 Remove leftover implementations for optional userbuffers support
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/misc.cu
  transformer_engine/pytorch/transformer.py
Labels: bug

#939 [PyTorch] Fix tp_group_initialized error
  transformer_engine/pytorch/attention.py
Labels: 1.8.0

#927 [C/PyTorch] Simplify THD offset tensors
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
  transformer_engine/common/fused_attn/fused_attn.cpp
  transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
  transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.h
  transformer_engine/common/fused_attn/utils.cu
  transformer_engine/common/fused_attn/utils.h
  transformer_engine/common/include/transformer_engine/fused_attn.h
  transformer_engine/jax/csrc/extensions/attention.cpp
  transformer_engine/paddle/csrc/custom_ops.cu
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/cpp_extensions/fused_attn.py
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/attention.cu
Labels: 1.8.0

#938 [PyTorch] Release GIL in PyTorch extensions
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
Labels: enhancement

#968 [PyTorch] Fix invalid import in test for context parallelism
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
Labels: bug, 1.8.0

#967 Replace functools cache with lru_cache
  build_tools/utils.py
  tests/pytorch/distributed/test_convergence.py
  tests/pytorch/fused_attn/test_fused_attn.py
  transformer_engine/pytorch/utils.py
Labels: bug, build
