Repository NVIDIA/TransformerEngine, pull requests merged in 2024-10, with the labels that each got.

#1220 Removed the unused options from GroupedLinear docs and fixed the bug with offsets
  transformer_engine/pytorch/module/grouped_linear.py
Labels: 1.11

#1191 [PyTorch] Minor optimizations to reduce CPU overheads in modules
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/cpu_offload.py
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/jit.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/grouped_linear.py
  transformer_engine/pytorch/module/layernorm.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/module/rmsnorm.py
  transformer_engine/pytorch/transformer.py
  transformer_engine/pytorch/utils.py
Labels: enhancement

#1202 [PyTorch] Debug dtype casting in operation-based API
  tests/pytorch/test_float8tensor.py
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/basic/bias.py
  transformer_engine/pytorch/ops/fused/backward_linear_add.py
  transformer_engine/pytorch/ops/fused/forward_linear_bias_activation.py
  transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
  transformer_engine/pytorch/tensor/__init__.py
  transformer_engine/pytorch/tensor/float8_tensor.py
Labels: bug

#1205 [JAX] Expose sliding window attn to TE-JAX API
  tests/jax/test_fused_attn.py
  tests/jax/test_layer.py
  tests/jax/test_praxis_layers.py
  tests/jax/utils.py
  transformer_engine/jax/attention.py
  transformer_engine/jax/cpp_extensions/attention.py
  transformer_engine/jax/csrc/extensions.h
  transformer_engine/jax/csrc/extensions/attention.cpp
  transformer_engine/jax/csrc/extensions/packing.cpp
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/praxis/transformer.py
Labels: enhancement, jax

#1240 Do not link against CUDA driver when building
  transformer_engine/common/CMakeLists.txt
Labels: bug, build

#1252 [PyTorch] Build custom ORT ops before running ONNX export tests
  qa/L0_pytorch_unittest/test.sh
  qa/L1_pytorch_context_parallel_test/test.sh
  tests/pytorch/custom_ort_ops/.gitignore
  tests/pytorch/custom_ort_ops/CMakeLists.txt
  tests/pytorch/custom_ort_ops/README.md
  tests/pytorch/custom_ort_ops/build.sh
  tests/pytorch/custom_ort_ops/custom_op_library.cc
  tests/pytorch/custom_ort_ops/custom_op_library.h
  tests/pytorch/libcustom_ort_fp8_qdq_ops.so
  tests/pytorch/test_onnx_export.py
  transformer_engine/pytorch/te_onnx_extensions.py
Labels: bug, testing

#1254 [PyTorch] Fix FP8 activation recompute
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: bug

#1228 [TE/JAX] Enabling CudaGraph for custom calls with FFI
  transformer_engine/jax/cpp_extensions/custom_call.py
  transformer_engine/jax/csrc/extensions/activation.cpp
  transformer_engine/jax/csrc/extensions/ffi.h
  transformer_engine/jax/csrc/extensions/transpose.cpp
Labels: jax

#1255 [PyTorch] Reorganize L1 tests
  qa/L0_pytorch_unittest/test.sh
  qa/L1_pytorch_context_parallel_test/test.sh
  qa/L1_pytorch_distributed_unittest/test.sh
  qa/L1_pytorch_onnx_test/test.sh
  qa/L3_pytorch_FA_versions_test/test.sh
  qa/L3_pytorch_convergence_test/test.sh
  tests/pytorch/distributed/test_fusible_ops.py
Labels: testing

#1265 [Paddle] Debug wheel test
  qa/L0_paddle_wheel/test.sh
Labels: bug, testing

#1273 [PyTorch] Remove PyTorch L0 distributed test
  qa/L0_pytorch_distributed_unittest/test.sh
Labels: testing

#1262 [JAX] Skip V100 encoder tests
  examples/jax/encoder/common.py
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
  examples/jax/encoder/test_multiprocessing_encoder.py
  examples/jax/encoder/test_single_gpu_encoder.py
  qa/L0_jax_unittest/test.sh
Labels: 1.12.0

#1286 [Paddle] Update type names for Paddle 3.0
  transformer_engine/paddle/csrc/custom_ops.cu
Labels: bug

#1274 Support building documentation in Python 3.12
  .github/workflows/docs.yml
  .gitignore
  docs/.gitignore
  docs/Makefile
  docs/conf.py
  docs/version_select.patch
Labels: bug, documentation

#1291 [PyTorch] Remove fast param getter from modules
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/grouped_linear.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: bug, 1.12.0
