Repository NVIDIA/TransformerEngine, pull requests merged in 2024-08, with the labels that each got.

#1052 [JAX] Add the missing 1HSS tests
  tests/jax/test_fused_attn.py
Labels: jax

#1081 Add user to TE CI
  .github/workflows/trigger-ci.yml
Labels: testing

#1027 [PyTorch] Branching operations
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/ops/__init__.py
  transformer_engine/pytorch/ops/basic/__init__.py
  transformer_engine/pytorch/ops/basic/add_in_place.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/basic/make_extra_output.py
  transformer_engine/pytorch/ops/fused/__init__.py
  transformer_engine/pytorch/ops/fused/backward_linear_add.py
  transformer_engine/pytorch/ops/fused/forward_linear_bias_activation.py
  transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
  transformer_engine/pytorch/ops/fuser.py
  transformer_engine/pytorch/ops/op.py
  transformer_engine/pytorch/ops/sequential.py
Labels: enhancement

#1091 Use minimal CUDA container for PyTorch GitHub build
  .github/workflows/build.yml
Labels: testing

#946 [TE/JAX] Prototype for New XLA Custom Calls with FFI
  build_tools/jax.py
  tests/jax/test_custom_call_compute.py
  transformer_engine/jax/cpp_extensions/activation.py
  transformer_engine/jax/cpp_extensions/custom_call.py
  transformer_engine/jax/cpp_extensions/misc.py
  transformer_engine/jax/cpp_extensions/transpose.py
  transformer_engine/jax/csrc/extensions.h
  transformer_engine/jax/csrc/extensions/activation.cpp
  transformer_engine/jax/csrc/extensions/ffi.cpp
  transformer_engine/jax/csrc/extensions/ffi.h
  transformer_engine/jax/csrc/extensions/misc.h
  transformer_engine/jax/csrc/extensions/normalization.cpp
  transformer_engine/jax/csrc/extensions/pybind.cpp
  transformer_engine/jax/csrc/extensions/transpose.cpp
Labels: enhancement, jax

#1118 Remove the commit hash from the release documentation
  docs/conf.py
Labels: 1.10.0

#1066 feat(pytorch): Allow TransformerLayer and MultiheadAttention to accept sequence length parameters
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/transformer.py
Labels: 1.10.0

#1083 Update FP8 scale-inverse in kernels with FP8 output
  tests/cpp/operator/test_cast_transpose.cu
  tests/cpp/operator/test_cast_transpose_dbias.cu
  tests/cpp/operator/test_cast_transpose_dbias_dgelu.cu
  tests/cpp/operator/test_layernorm.cu
  tests/cpp/operator/test_multi_cast_transpose.cu
  tests/cpp/operator/test_rmsnorm.cu
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/activation/activation_template.h
  transformer_engine/common/common.cu
  transformer_engine/common/common.h
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/common/layer_norm/ln.h
  transformer_engine/common/layer_norm/ln_api.cpp
  transformer_engine/common/layer_norm/ln_fwd_kernels.cuh
  transformer_engine/common/rmsnorm/rmsnorm_api.cpp
  transformer_engine/common/rmsnorm/rmsnorm_fwd_kernels.cuh
  transformer_engine/common/transpose/cast_transpose.cu
  transformer_engine/common/transpose/cast_transpose_fusion.cu
  transformer_engine/common/transpose/multi_cast_transpose.cu
  transformer_engine/common/transpose/rtc/cast_transpose.cu
  transformer_engine/common/transpose/rtc/cast_transpose_fusion.cu
  transformer_engine/common/util/cast.cu
  transformer_engine/common/util/vectorized_pointwise.h
  transformer_engine/common/utils.cuh
  transformer_engine/pytorch/cpp_extensions/_common.py
  transformer_engine/pytorch/cpp_extensions/activation.py
  transformer_engine/pytorch/cpp_extensions/cast.py
  transformer_engine/pytorch/cpp_extensions/normalization.py
  transformer_engine/pytorch/cpp_extensions/transpose.py
  transformer_engine/pytorch/float8_tensor.py
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/te_onnx_extensions.py
Labels: performance

#1114 Add FP8 support to CP implementation with KV P2P
  tests/pytorch/fused_attn/run_fused_attn_with_cp.py
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
  transformer_engine/pytorch/attention.py
Labels: 1.10.0

#1073 [PyTorch] Add support for padding mask in `UnfusedDotProductAttention`
  tests/pytorch/test_numerics.py
  transformer_engine/common/fused_attn/fused_attn.cpp
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/softmax.py
  transformer_engine/pytorch/transformer.py
Labels: 1.10.0

#1124 Re-add framework specific required dependencies for source build
  setup.py
Labels: bug, build, 1.10.0

#936 [MoE][Common/PyTorch] Add permutation
  tests/pytorch/test_permutation.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/common/include/transformer_engine/permutation.h
  transformer_engine/common/permutation/permutation.cu
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/permutation.cu
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/permutation.py
Labels: enhancement

#1136 Hide non-necessary symbols from shared object
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/libtransformer_engine.version
Labels: bug, build, 1.10.0

#1141 [PyTorch] Fix FP8 logic related to FA2/FA3
  tests/pytorch/fused_attn/test_fused_attn.py
  transformer_engine/pytorch/attention.py
Labels: 1.11

#1134 Fix QKV dtype in the bwd of FP8+CP
  transformer_engine/pytorch/attention.py
Labels: 1.10.0
