Repository NVIDIA/TransformerEngine, pull requests merged in 2024-01, with the labels that each got.

#510 [PyTorch] Reduce size of sanity tests
  tests/pytorch/test_sanity.py
Labels: testing

#590 [PyTorch] Refactor parameter splitting in Linear and LayerNormLinear
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/linear.py
Labels: bug

#596 [PyTorch] Deferred Initialization via `device='meta'` option
  examples/pytorch/fsdp/README.md
  examples/pytorch/fsdp/fsdp.py
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/module/rmsnorm.py
  transformer_engine/pytorch/utils.py
Labels: enhancement, 1.3.0

#557 make TransformerLayer accept a `bshd` or `sbhd` tensor format
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/transformer.py
Labels: 1.3.0

#607 Switch to torch.compile for dropout for torch v>2.2
  transformer_engine/pytorch/jit.py
Labels: 1.3.0

#571 Activation offloading to CPU's for the Linear, Layernorm Linear and the Layernorm MLP modules
  docs/api/pytorch.rst
  tests/pytorch/test_sanity.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/cpu_offload.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: 1.3.0

#626 [PyTorch] Workaround for incorrect output from torch.cuda.is_bf16_compatible() on V100s and TU102s
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/test_numerics.py
  tests/pytorch/test_sanity.py
  transformer_engine/pytorch/utils.py
Labels: bug, 1.3.0

#621 [PyTorch] forward attention_type in MultiHeadAttention
  transformer_engine/pytorch/attention.py
Labels: bug

#627 Fix compatibility with pyTorch 2.0
  transformer_engine/pytorch/jit.py
Labels: bug, 1.3.0

#532 [JAX] Custom Op Workspace Tensors from XLA Buffers
  .gitignore
  tests/jax/test_custom_call_compute.py
  transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
  transformer_engine/common/fused_attn/fused_attn_f16_max512_seqlen.cu
  transformer_engine/common/fused_attn/fused_attn_fp8.cu
  transformer_engine/common/layer_norm/ln_api.cpp
  transformer_engine/common/rmsnorm/rmsnorm_api.cpp
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/csrc/extensions.cpp
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/jax/csrc/modules.h
  transformer_engine/jax/csrc/utils.h
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/mlp.py
Labels: enhancement

#633 [Paddle] Replace paddle.fluid imports with paddle.base
  qa/L0_paddle_lint/test.sh
  tests/paddle/dist_launcher.py
  transformer_engine/paddle/layer/base.py
  transformer_engine/paddle/profile.py
Labels: bug

#647 [PyTorch] Do not allocate FP8 workspace buffers when params are FP8
  transformer_engine/pytorch/module/base.py
Labels: bug

#645 Fused rope compute in fp32
  transformer_engine/common/fused_rope/fused_rope.cu
Labels: bug, 1.4.0
