Repository NVIDIA/TransformerEngine, pull requests merged in 2024-09, with the labels that each got.

#1148 Improvements for building wheels
  build_tools/utils.py
  build_tools/wheel_utils/Dockerfile.aarch
  build_tools/wheel_utils/Dockerfile.x86
  build_tools/wheel_utils/build_wheels.sh
  qa/L0_jax_wheel/test.sh
  qa/L0_paddle_wheel/test.sh
  qa/L0_pytorch_wheel/test.sh
  qa/L1_pytorch_distributed_unittest/test.sh
  setup.py
  transformer_engine/common/__init__.py
  transformer_engine/jax/__init__.py
  transformer_engine/paddle/__init__.py
  transformer_engine/pytorch/__init__.py
Labels: build, 1.10.0

#1180 Update CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#1181 Update CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#1185 [PyTorch] Port fused optimizer tests to pytest
  tests/pytorch/test_fused_optimizer.py
Labels: testing

#1175 [PyTorch] Check network interface name when initializing Userbuffers
  transformer_engine/pytorch/module/base.py
Labels: bug

#1198 Update list of CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#1203 Update list of CI users
  .github/workflows/trigger-ci.yml
Labels: testing
