Repository NVIDIA/TransformerEngine, pull requests merged in 2024-07, with the labels that each got.

#983 [Core] Fix bug when selecting tuned RMSNorm kernels
  transformer_engine/common/rmsnorm/rmsnorm_api.cpp
Labels: bug

#970 [PyTorch] Runtime lookup for CUDA Driver API calls in Userbuffers
  build_tools/pytorch.py
  transformer_engine/common/util/cuda_driver.cpp
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
Labels: bug, 1.8.0

#974 Add test for building without support for any DL frameworks
  .github/workflows/build.yml
  docs/installation.rst
Labels: testing

#1000 [TE/JAX] Remove tuple wrapper of singleton in HLO lowering return
  transformer_engine/jax/cpp_extensions/activation.py
  transformer_engine/jax/cpp_extensions/softmax.py
  transformer_engine/jax/cpp_extensions/transpose.py
Labels: bug

#707 [PyTorch] Prototype for operation-based API
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/test_fusible_ops.py
  tests/pytorch/test_fusible_ops_distributed.py
  tests/pytorch/test_recipe.py
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/float8_tensor.py
  transformer_engine/pytorch/ops/__init__.py
  transformer_engine/pytorch/ops/_common.py
  transformer_engine/pytorch/ops/basic/__init__.py
  transformer_engine/pytorch/ops/basic/all_gather.py
  transformer_engine/pytorch/ops/basic/all_reduce.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/basic/bias.py
  transformer_engine/pytorch/ops/basic/identity.py
  transformer_engine/pytorch/ops/basic/reduce_scatter.py
  transformer_engine/pytorch/ops/basic/reshape.py
  transformer_engine/pytorch/ops/fused_forward/__init__.py
  transformer_engine/pytorch/ops/fused_forward/linear_bias_activation.py
  transformer_engine/pytorch/ops/fuser.py
  transformer_engine/pytorch/ops/linear.py
  transformer_engine/pytorch/ops/op.py
  transformer_engine/pytorch/ops/sequential.py
  transformer_engine/pytorch/utils.py
Labels: enhancement

#1002 Reduce CUDA driver calls when choosing transpose kernels
  transformer_engine/common/transpose/cast_transpose.cu
  transformer_engine/common/transpose/cast_transpose_fusion.cu
  transformer_engine/common/transpose/transpose.cu
Labels: bug

#1001 Simplify logic for launching CI
  .github/workflows/blossom-ci.yml
  .github/workflows/trigger-ci.yml
Labels: testing

#1021 [Paddle] Compile with paddlepaddle-gpu 2.6.1
  build_tools/paddle.py
  transformer_engine/paddle/csrc/custom_ops.cu
Labels: 1.9.0

#1028 [PyTorch] Update Sequential container to handle changes in module base class
  transformer_engine/pytorch/ops/sequential.py
Labels: bug

#986 [PyTorch] Fixing hang in `initialize_ub()` for multi-node runs after PR901 removal of MPI-dependence
  build_tools/pytorch.py
  examples/pytorch/comm_gemm_overlap/README.md
  examples/pytorch/comm_gemm_overlap/ln_mlp_with_overlap.py
  tests/pytorch/distributed/run_gemm_with_overlap.py
  tests/pytorch/distributed/test_comm_gemm_overlap.py
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/userbuffers/ipcsocket.cc
  transformer_engine/pytorch/csrc/userbuffers/ipcsocket.h
  transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.cu
  transformer_engine/pytorch/csrc/userbuffers/userbuffers.h
  transformer_engine/pytorch/module/base.py
Labels: bug

#1037 Update minimum CMake version
  .github/workflows/build.yml
  setup.py
  transformer_engine/common/CMakeLists.txt
Labels: build, 1.9.0

#1038 [JAX] Debug distributed attention tests
  tests/jax/test_distributed_fused_attn.py
Labels: bug, 1.9.0

#1040 Fix build error with Paddle >2.6.1
  transformer_engine/paddle/csrc/custom_ops.cu
Labels: bug, 1.9.0

#1041 [PyTorch] Fix linter warnings
  transformer_engine/pytorch/csrc/comm_gemm_overlap.h
  transformer_engine/pytorch/csrc/userbuffers/userbuffers-host.cpp
Labels: 1.9.0

#1042 Fixes for pip wheels
  build_tools/wheel_utils/build_wheels.sh
  qa/L0_paddle_wheel/test.sh
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/pycudnn.cpp
Labels: 1.9.0
