Repository NVIDIA/TransformerEngine, pull requests merged in 2024-11, with the labels that each got.

#1305 [PyTorch] Missing intra-domain ranks list when initializing Userbuffers with data parallelism
  transformer_engine/pytorch/module/base.py
Labels: 0.13.0

#1117 [PyTorch] Debug CUDA graph support with operation-based API
  tests/pytorch/test_cuda_graphs.py
  transformer_engine/pytorch/fp8.py
  transformer_engine/pytorch/graph.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/basic/bias.py
  transformer_engine/pytorch/ops/fuser.py
  transformer_engine/pytorch/ops/op.py
Labels: bug

#1063 [PyTorch] Debug checkpointing with operation-based API
  tests/pytorch/test_torch_save_load.py
  transformer_engine/pytorch/ops/linear.py
  transformer_engine/pytorch/ops/op.py
Labels: bug

#1033 [PyTorch] Normalization ops
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/module/layernorm.py
  transformer_engine/pytorch/module/rmsnorm.py
  transformer_engine/pytorch/ops/__init__.py
  transformer_engine/pytorch/ops/_common.py
  transformer_engine/pytorch/ops/basic/__init__.py
  transformer_engine/pytorch/ops/basic/layer_norm.py
  transformer_engine/pytorch/ops/basic/quantize.py
  transformer_engine/pytorch/ops/basic/rmsnorm.py
  transformer_engine/pytorch/ops/fuser.py
  transformer_engine/pytorch/ops/op.py
Labels: enhancement

#1316 Update list of CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#1320 [PyTorch] Fix ONNX export bug with operation-based API
  transformer_engine/pytorch/ops/op.py
Labels: bug

#1334 [PyTorch] Fix multiple calls to saved_tensors in CP attention
  transformer_engine/pytorch/attention.py
Labels: bug

#1164 [PyTorch] Activation operations
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/cpp_extensions/transpose.py
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/extensions/transpose.cpp
  transformer_engine/pytorch/ops/basic/__init__.py
  transformer_engine/pytorch/ops/basic/activation.py
Labels: 1.13.0

#1328 [PyTorch] Fix GQA error message
  transformer_engine/pytorch/attention.py
Labels: 1.13.0

#1329 [PyTorch] Integration test for Megatron-LM
  qa/L1_pytorch_mcore_integration/test.sh
  transformer_engine/pytorch/module/layernorm.py
  transformer_engine/pytorch/module/rmsnorm.py
  transformer_engine/pytorch/ops/basic/layer_norm.py
  transformer_engine/pytorch/ops/basic/rmsnorm.py
  transformer_engine/pytorch/ops/fuser.py
Labels: bug, 1.13.0
