Repository NVIDIA/TransformerEngine, pull requests merged in 2024-12, with the labels that each got.

#1340 Update list of CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#1338 Debug nightly docs
  .github/workflows/deploy_nightly_docs.yml
  .github/workflows/docs.yml
Labels: documentation, testing

#1335 [PyTorch] Store module extra state in tensor
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/ops/op.py
Labels: bug, 1.14.0

#1357 Disable FP8 in Mcore integration test on older GPUs
  qa/L1_pytorch_mcore_integration/.gitignore
  qa/L1_pytorch_mcore_integration/merges.txt
  qa/L1_pytorch_mcore_integration/test.sh
Labels: bug, testing, 1.14.0

#1366 [JAX] Bug fix for distributed normalization
  transformer_engine/common/normalization/common.h
  transformer_engine/jax/cpp_extensions/normalization.py
  transformer_engine/jax/csrc/extensions/pybind.cpp
Labels: 1.14.0

#1370 [common] Add max_t support for KV in THD
  transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
Labels: 1.14.0

#1374 [PyTorch] Add weights_only=False for torch.load
  tests/pytorch/test_float8tensor.py
  tests/pytorch/test_sanity.py
  tests/pytorch/test_torch_save_load.py
Labels: 1.14.0

#1281 [PyTorch] Fix get_swa_mask() for padding masks
  tests/pytorch/fused_attn/test_fused_attn.py
  transformer_engine/pytorch/attention.py
Labels: 1.14.0
