Repository NVIDIA/TransformerEngine, pull requests merged in 2024-02, with the labels that each got.

#643 [JAX] Fix unfused GQA performance
  qa/L0_jax_distributed_unittest/test.sh
  qa/L0_jax_unittest/test.sh
  transformer_engine/jax/flax/transformer.py
Labels: enhancement, jax

#630 [PyTorch] Refactor caching of cumulative sequence lengths
  transformer_engine/pytorch/attention.py
Labels: bug

#659 [PyTorch] Fix pipeline parallel execution by using cloned scale inverse tensors
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
Labels: bug

#593 Implement fused kernel for FP8 scale update
  tests/paddle/test_operators.py
  tests/pytorch/test_recipe.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/include/transformer_engine/recipe.h
  transformer_engine/common/recipe/__init__.py
  transformer_engine/common/recipe/delayed_scaling.cu
  transformer_engine/paddle/csrc/common.h
  transformer_engine/paddle/csrc/custom_ops.cu
  transformer_engine/paddle/fp8.py
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/extensions/recipe.cu
  transformer_engine/pytorch/fp8.py
Labels: enhancement, 1.4.0

#662 [PyTorch] Add Float8Tensor option to avoid updating transpose cache when possible
  tests/pytorch/test_float8tensor.py
  transformer_engine/pytorch/float8_tensor.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: bug

#490 Use unoptimized layernorm kernel if pointers are not aligned
  transformer_engine/common/layer_norm/ln.h
  transformer_engine/common/layer_norm/ln_api.cpp
  transformer_engine/common/utils.cuh
Labels: bug, 1.4.0

#673 Move distributed tests to L1
  qa/L1_jax_distributed_unittest/test.sh
  qa/L1_pytorch_context_parallel_test/test.sh
Labels: testing

#675 Add `__version__` attribute to Python module
  VERSION
  setup.py
  te_version.py
  transformer_engine/__init__.py
  transformer_engine/_version.py
Labels: build

#653 [JAX] Refine MHA API and add DPA API
  docs/api/jax.rst
  tests/jax/test_fused_attn.py
  tests/jax/test_layer.py
  tests/jax/test_praxis_layers.py
  tests/jax/utils.py
  transformer_engine/common/fused_attn/fused_attn.cpp
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/csrc/extensions.cpp
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/jax/csrc/modules.h
  transformer_engine/jax/flax/__init__.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/fused_attn.py
  transformer_engine/jax/praxis/__init__.py
  transformer_engine/jax/praxis/transformer.py
Labels: jax

#670 [PyTorch] Non-reentrant mode for activation recompute
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/module/layernorm_mlp.py
Labels: enhancement

#655 [JAX] Support various implementations of RoPE.
  tests/jax/test_layer.py
  tests/jax/test_praxis_layers.py
  tests/jax/utils.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/praxis/transformer.py
Labels: jax

#664 [JAX] Bugfix for softmax primitives accepting invalid input sharding
  tests/jax/test_distributed_softmax.py
  transformer_engine/jax/cpp_extensions.py
Labels: bug, jax
