Repository NVIDIA/TransformerEngine, pull requests merged in 2024-05, with the labels that each got.

#774 [JAX] Support FP8 training for Pipeline Parallelism when Micro-batch > 1 on Paxml.
  .github/workflows/build.yml
  transformer_engine/jax/dot.py
  transformer_engine/jax/fp8.py
  transformer_engine/jax/layernorm.py
  transformer_engine/jax/mlp.py
Labels: jax

#810 [JAX] Generalizing Activation Primitives
  tests/jax/test_custom_call_compute.py
  transformer_engine/common/transpose/cast_transpose_fusion.cu
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/csrc/extensions.cpp
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/jax/csrc/modules.h
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/mlp.py
Labels: enhancement, jax

#834 [PyTorch] Update FP8 recipe test to handle recipe changes
  tests/pytorch/test_recipe.py
Labels: bug

#839 Import framework submodules lazily
  transformer_engine/__init__.py
Labels: enhancement

#826 [JAX] Adding Gated/Non-gated ReLU, Quick GeLU, Squared ReLU
  tests/jax/test_custom_call_compute.py
  transformer_engine/common/activation/gelu.cu
  transformer_engine/common/activation/relu.cu
  transformer_engine/common/activation/swiglu.cu
  transformer_engine/common/include/transformer_engine/activation.h
  transformer_engine/common/include/transformer_engine/transpose.h
  transformer_engine/common/transpose/cast_transpose_fusion.cu
  transformer_engine/common/util/math.h
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/csrc/extensions.cpp
  transformer_engine/jax/csrc/modules.cpp
  transformer_engine/jax/csrc/modules.h
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/mlp.py
Labels: enhancement, jax, 1.7.0

#831 Replace FindCUDNN.cmake with cudnn-frontend's cuDNN.cmake
  transformer_engine/CMakeLists.txt
  transformer_engine/cmake/FindCUDNN.cmake
  transformer_engine/common/CMakeLists.txt
Labels: 1.7.0

#846 [Pytorch] Added squared ReLU implementation
  tests/pytorch/test_numerics.py
  tests/pytorch/test_sanity.py
  transformer_engine/pytorch/cpp_extensions/activation.py
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/activation.cu
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/ts_fp8_op.cpp
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/transformer.py
Labels: 1.7.0

#818 [PyTorch/Jax] Fix attention mask definition, and sliding window for decoder
  README.rst
  tests/jax/test_fused_attn.py
  tests/jax/utils.py
  tests/pytorch/fused_attn/test_fused_attn.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/transformer.py
Labels: 1.7.0

#771 [PyTorch] Fixed bug with loading calibrated weights
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/test_torch_save_load.py
  transformer_engine/pytorch/module/base.py
Labels: bug, 1.7.0

#860 [PyTorch] Replaced deprecated `pkg_resources` with `packaging`
  setup.py
  transformer_engine/pytorch/attention.py
Labels: bug, 1.7.0

#845 [Common] Added Alignment Requirements for CuBLAS heuristics
  tests/pytorch/test_sanity.py
  transformer_engine/common/gemm/cublaslt_gemm.cu
Labels: bug, 1.7.0

#859 [JAX] Fixed the shape miss-matching issue in MLP.
  tests/jax/test_layer.py
  transformer_engine/jax/flax/module.py
Labels: bug, 1.7.0

#791 [PyTorch] Support `torch.amp.autocast` in TE checkpoint
  transformer_engine/pytorch/distributed.py
Labels: bug, 1.7.0

#874 Add user to TE CI
  .github/workflows/trigger-ci.yml
Labels: testing

#852 Use correct FP8 group in multi-GPU docs
  docs/examples/advanced_optimizations.ipynb
Labels: documentation, 1.7.0

#875 [PyTorch] Make sure RoPE frequencies are in FP32
  transformer_engine/pytorch/attention.py
Labels: bug, 1.7.0

#876 New NVIDIA footer in documentation
  .github/workflows/docs.yml
  docs/_static/NVIDIA-LogoBlack.svg
  docs/_static/css/nvidia_footer.css
  docs/_templates/footer.html
  docs/_templates/layout.html
  docs/conf.py
Labels: documentation, 1.7.0

#820 [PyTorch] Refactor FP8 workspaces in linear modules
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/test_float8tensor.py
  transformer_engine/pytorch/float8_tensor.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: bug, enhancement

#882 [PyTorch] Replace `int8_t` in Pybind11 extensions with `int64_t`
  transformer_engine/pytorch/csrc/ts_fp8_op.cpp
Labels: bug
