Repository NVIDIA/TransformerEngine, pull requests merged in 2024-03, with the labels that each got.

#615 Create a small tutorial on how to accelerate HF Llama models with Transformer-Engine
  docs/examples/te_llama/media/llama_for_causal_lm.svg
  docs/examples/te_llama/media/llama_zoom.svg
  docs/examples/te_llama/media/llamadecoderlayer.svg
  docs/examples/te_llama/media/model_change.svg
  docs/examples/te_llama/media/swiglu.svg
  docs/examples/te_llama/media/swiglu_te.svg
  docs/examples/te_llama/media/tellamadecoderlayer.svg
  docs/examples/te_llama/media/transformer_llama.png
  docs/examples/te_llama/media/transformer_vs_llama.svg
  docs/examples/te_llama/media/weight_swap.svg
  docs/examples/te_llama/te_llama.py
  docs/examples/te_llama/tutorial_accelerate_hf_llama_with_te.ipynb
  docs/examples/te_llama/utils.py
  docs/index.rst
Labels: 1.4.0

#684 Enable incremental CMake build
  setup.py
Labels: build

#695 [PyTorch] Update doc for checkpoint API
  transformer_engine/pytorch/distributed.py
Labels: documentation

#704 Fix types for forward attention for JAX.
  transformer_engine/jax/cpp_extensions.py
  transformer_engine/jax/fused_attn.py
Labels: jax

#668 [PyTorch] Adjusted the logic of MHA and DPA to enable speculative decoding
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/softmax.py
Labels: enhancement

#696 [Common] Fix build errors with recent cuDNN frontend versions
  transformer_engine/common/fused_attn/fused_attn_fp8.cu
Labels: bug, build

#722 Rachitg/dp carveout
  transformer_engine/pytorch/csrc/ts_fp8_op.cpp
Labels: 1.5.0

#720 Llama accelerate tutorial
  docs/examples/te_llama/te_llama.py
  docs/examples/te_llama/tutorial_accelerate_hf_llama_with_te.ipynb
  docs/examples/te_llama/utils.py
Labels: 1.5.0

#740 [PyTorch] Fix backward compatibility with checkpoint API
  transformer_engine/pytorch/distributed.py
Labels: 1.5.0

#730 Llama tutorial fixes
  docs/examples/te_llama/te_llama.py
  docs/examples/te_llama/tutorial_accelerate_hf_llama_with_te.ipynb
  docs/examples/te_llama/utils.py
Labels: 1.5.0
