Repository NVIDIA/TransformerEngine, pull requests merged in 2025-09, with the labels that each got.

#2142 Fix bug when enabling --overlap-grad-reduce in mcore
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/grouped_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
Labels: bug, 2.7.0

#2158 [PyTorch] Support activation CPU offloading in fusible ops
  tests/pytorch/test_cpu_offloading.py
  transformer_engine/pytorch/ops/_common.py
  transformer_engine/pytorch/ops/basic/activation.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/basic/dropout.py
  transformer_engine/pytorch/ops/basic/l2normalization.py
  transformer_engine/pytorch/ops/basic/layer_norm.py
  transformer_engine/pytorch/ops/basic/rmsnorm.py
  transformer_engine/pytorch/ops/fused/forward_linear_bias_activation.py
  transformer_engine/pytorch/ops/fused/forward_linear_bias_add.py
  transformer_engine/pytorch/ops/fused/forward_linear_scale_add.py
  transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py
Labels: bug, enhancement, testing

#2185 Fix cuDNN version checks when getting backend and for sm89 kv cache
  transformer_engine/common/fused_attn/fused_attn.cpp
  transformer_engine/pytorch/attention/dot_product_attention/utils.py
Labels: 2.8.0

#2166 [JAX] CollectiveGemm
  build_tools/jax.py
  examples/jax/collective_gemm/common.py
  examples/jax/collective_gemm/conftest.py
  examples/jax/collective_gemm/run_test_cgemm.sh
  examples/jax/collective_gemm/test_dense_grad.py
  examples/jax/collective_gemm/test_gemm.py
  examples/jax/collective_gemm/test_layernorm_mlp_grad.py
  qa/L0_jax_distributed_unittest/test.sh
  transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
  transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
  transformer_engine/common/include/transformer_engine/comm_gemm_overlap.h
  transformer_engine/common/util/logging.h
  transformer_engine/jax/cpp_extensions/gemm.py
  transformer_engine/jax/cpp_extensions/misc.py
  transformer_engine/jax/csrc/extensions.h
  transformer_engine/jax/csrc/extensions/cgemm_helper.cpp
  transformer_engine/jax/csrc/extensions/cgemm_helper.h
  transformer_engine/jax/csrc/extensions/gemm.cpp
  transformer_engine/jax/csrc/extensions/misc.h
  transformer_engine/jax/csrc/extensions/pybind.cpp
  transformer_engine/jax/dense.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/layernorm_mlp.py
  transformer_engine/jax/sharding.py
Labels: 2.8.0

#2214 Fix the segfault in the nvfp4 quantization
  transformer_engine/common/util/nvfp4_transpose.cuh
Labels: 2.8.0
