Repository NVIDIA/TransformerEngine, pull requests merged in 2025-03, with the labels that each got.

#1528 [PyTorch] Set flags in norm modules for Mcore sequence-parallel support
  transformer_engine/pytorch/module/layernorm.py
  transformer_engine/pytorch/module/rmsnorm.py
Labels: bug

#1519 [common] Removed tensor boundary checks in MXFP8 kernels
  transformer_engine/common/util/cast_kernels.cuh
Labels: performance

#1535 Update list of CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#1470 Add support for UB MNNVL
  examples/pytorch/comm_gemm_overlap/te_layer_with_overlap.py
  tests/pytorch/distributed/run_gemm_with_overlap.py
  tests/pytorch/distributed/run_layer_with_overlap.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
  transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.cu
  transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.h
  transformer_engine/common/util/cuda_driver.cpp
  transformer_engine/common/util/cuda_nvml.cpp
  transformer_engine/common/util/cuda_nvml.h
  transformer_engine/common/util/shared_lib_wrapper.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/comm_gemm_overlap.cpp
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/module/base.py
Labels: 2.2.0

#1380 Don't touch nor send messages to the root logger.
  transformer_engine/jax/__init__.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/attention.py
Labels: 2.2.0

#1526 Fix installation from PyPI wheels after a source install
  build_tools/build_ext.py
  examples/jax/encoder/common.py
  pylintrc
  tests/jax/conftest.py
  tests/jax/test_fused_attn.py
  transformer_engine/common/__init__.py
  transformer_engine/jax/__init__.py
  transformer_engine/jax/attention.py
  transformer_engine/jax/cpp_extensions/activation.py
  transformer_engine/jax/cpp_extensions/attention.py
  transformer_engine/jax/cpp_extensions/custom_call.py
  transformer_engine/jax/cpp_extensions/misc.py
  transformer_engine/jax/cpp_extensions/normalization.py
  transformer_engine/jax/cpp_extensions/quantization.py
  transformer_engine/jax/cpp_extensions/softmax.py
  transformer_engine/jax/cpp_extensions/transpose.py
  transformer_engine/jax/fp8.py
  transformer_engine/jax/setup.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/setup.py
Labels: bug, build, 2.1.0

#1536 [PyTorch] Move Lightning-Thunder integration test to L1
  qa/L0_pytorch_unittest/test.sh
  qa/L1_pytorch_thunder_integration/test.sh
Labels: bug, testing

#1539 make sure dout is contiguous
  transformer_engine/pytorch/attention.py
Labels: 2.2.0

#1549 [PyTorch] Fix incorrect docstrings in tensor saving functions
  transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py
  transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
  transformer_engine/pytorch/tensor/float8_tensor.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
Labels: documentation

#1521 [PyTorch] Remove Megatron-LM convergence test
  qa/L3_pytorch_convergence_test/test.sh
  tests/pytorch/distributed/print_logs.py
  tests/pytorch/distributed/run_megatron_lm_gpt.sh
  tests/pytorch/distributed/test_convergence.py
Labels: testing, 2.2.0

#1550 Disable parallelism in core build test
  .github/workflows/build.yml
Labels: testing

#1486 Explicitly use `python3` and `pip3` executables
  README.rst
  docs/installation.rst
  qa/L0_cppunittest/test.sh
  qa/L0_jax_distributed_unittest/test.sh
  qa/L0_jax_lint/test.sh
  qa/L0_jax_unittest/test.sh
  qa/L0_jax_wheel/test.sh
  qa/L0_license/copyright_checker.py
  qa/L0_license/test.sh
  qa/L0_pytorch_lint/test.sh
  qa/L0_pytorch_unittest/test.sh
  qa/L0_pytorch_wheel/test.sh
  qa/L1_pytorch_distributed_unittest/test.sh
  qa/L1_pytorch_mcore_integration/test.sh
  qa/L3_pytorch_FA_versions_test/test.sh
  qa/format.sh
  tests/cpp/CMakeLists.txt
  tests/pytorch/distributed/test_comm_gemm_overlap.py
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
  transformer_engine/jax/__init__.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/attention.py
Labels: testing

#1505 Support tensors with only column-wise data
  tests/cpp/operator/test_normalization_mxfp8.cu
  tests/cpp/test_common.cu
  transformer_engine/common/common.h
  transformer_engine/common/include/transformer_engine/transformer_engine.h
  transformer_engine/common/transformer_engine.cpp
  transformer_engine/pytorch/cpu_offload.py
  transformer_engine/pytorch/csrc/extensions/type_converters.cpp
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py
  transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
  transformer_engine/pytorch/tensor/float8_tensor.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
  transformer_engine/pytorch/tensor/quantized_tensor.py
Labels: enhancement, performance

#1542 Refactoring attention.py part 1
  docs/api/pytorch.rst
  docs/examples/attention/attention.ipynb
  docs/examples/te_llama/te_llama.py
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
  tests/pytorch/test_fused_rope.py
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/dot_product_attention/__init__.py
  transformer_engine/pytorch/dot_product_attention/inference.py
  transformer_engine/pytorch/dot_product_attention/rope.py
  transformer_engine/pytorch/dot_product_attention/utils.py
  transformer_engine/pytorch/transformer.py
Labels: 2.2.0

#1577 Update full recompute feature to save recipe.
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/distributed.py
Labels: 2.2.0

#1355 Add KV cache for paged/non-paged attention
  qa/L0_pytorch_unittest/test.sh
  qa/L3_pytorch_FA_versions_test/test.sh
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/fused_attn/test_paged_attn.py
  tests/pytorch/test_numerics.py
  transformer_engine/common/fused_attn/fused_attn.cpp
  transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu
  transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.h
  transformer_engine/common/fused_attn/fused_attn_fp8.cu
  transformer_engine/common/fused_attn/utils.cu
  transformer_engine/common/fused_attn/utils.h
  transformer_engine/common/include/transformer_engine/fused_attn.h
  transformer_engine/common/util/pybind_helper.h
  transformer_engine/jax/csrc/extensions/attention.cpp
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/constants.py
  transformer_engine/pytorch/cpp_extensions/fused_attn.py
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/attention.cu
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/kv_cache.cuh
  transformer_engine/pytorch/dot_product_attention/inference.py
  transformer_engine/pytorch/dot_product_attention/utils.py
  transformer_engine/pytorch/graph.py
Labels: 2.2.0

#1574 Fix issues in fused_attn_bwd
  tests/pytorch/fused_attn/run_fused_attn_with_cp.py
  transformer_engine/pytorch/attention.py
Labels: 2.2.0

#1596 Ensure weight transpose is valid for Hopper FP8 training
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: bug, 2.2.0

#1600 [JAX] Fixing importing in the encoder examples
  examples/jax/encoder/common.py
Labels: 2.2.0

#1589 [PyTorch] Minor fixes for TE 2.2
  docs/api/pytorch.rst
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/fused_attn/test_kv_cache.py
  tests/pytorch/test_numerics.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/dot_product_attention/inference.py
Labels: 2.2.0

#1581 [PyTorch] Optimize MXFP8 all-gathers
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: 2.2.0

#1606 [PyTorch] Add tests for current scaling; misc related fixes
  tests/pytorch/test_cuda_graphs.py
  tests/pytorch/test_sanity.py
  transformer_engine/common/recipe/current_scaling.cu
  transformer_engine/pytorch/ops/op.py
Labels: 2.2.0

#1621 [PyTorch] Support default process group with FP8 current scaling
  tests/pytorch/distributed/run_numerics.py
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions/quantizer.cpp
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/tensor/float8_tensor.py
  transformer_engine/pytorch/utils.py
Labels: bug
