Repository NVIDIA/TransformerEngine, pull requests merged in 2025-01, with the labels that each got.

#1343 [PyTorch] Adding TP overlap support for `te.Linear` with `parallel_mode="column"`
  tests/pytorch/distributed/run_layer_with_overlap.py
  tests/pytorch/distributed/test_comm_gemm_overlap.py
  transformer_engine/pytorch/module/linear.py
Labels: enhancement, 1.14.0

#1403 [PyTorch] Avoid `parameters` function in op backward pass
  transformer_engine/pytorch/ops/fuser.py
Labels: bug

#1426 [PyTorch] Fix linter warnings
  qa/L1_pytorch_distributed_unittest/test.sh
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/grouped_linear.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/fused/userbuffers_backward_linear.py
  transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py
Labels: bug, 2.0.0

#1431 Pad MXFP8 scale inverses at the time of creation
  qa/L0_pytorch_unittest/test.sh
  tests/cpp/run_norm_tests.sh
  transformer_engine/common/common.h
  transformer_engine/common/swizzle/swizzle.cu
  transformer_engine/common/transformer_engine.cpp
  transformer_engine/pytorch/csrc/common.cpp
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/quantizer.cpp
  transformer_engine/pytorch/csrc/extensions/swizzle.cpp
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
  transformer_engine/pytorch/utils.py
Labels: 2.0.0

#1440 [PyTorch] Respect existing quantizer usages in functional linear API
  transformer_engine/pytorch/ops/basic/basic_linear.py
Labels: bug, 2.0.0

#1444 [PyTorch] Debug NeMo distributed optimizer
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/tensor/float8_tensor.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
Labels: bug, 2.0.0
