Repository NVIDIA/TransformerEngine, pull requests merged in 2025-02, with the labels that each got.

#1437 [common] Generalized MXFP8 fused kernels w.r.t. input tensor dimensions
  tests/cpp/operator/test_cast_mxfp8.cu
  tests/cpp/operator/test_dequantize_mxfp8.cu
  tests/cpp/test_common.cu
  tests/cpp/test_common.h
  transformer_engine/common/common.cu
  transformer_engine/common/common.h
  transformer_engine/common/util/cast_kernels.cuh
  transformer_engine/common/util/dequantize_kernels.cuh
  transformer_engine/common/utils.cuh
Labels: enhancement, 2.0.0

#1450 [Core] Debug unaligned MXFP8 dequantize tests
  tests/cpp/operator/test_dequantize_mxfp8.cu
Labels: bug, testing, 2.0.0

#1427 [PyTorch/C++] Comm+GEMM overlap compatibility with QuantizedTensor
  tests/pytorch/distributed/run_gemm_with_overlap.py
  tests/pytorch/distributed/run_layer_with_overlap.py
  tests/pytorch/distributed/test_comm_gemm_overlap.py
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/test_sanity.py
  transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
  transformer_engine/common/include/transformer_engine/comm_gemm_overlap.h
  transformer_engine/common/normalization/layernorm/ln_api.cpp
  transformer_engine/common/normalization/rmsnorm/rmsnorm_api.cpp
  transformer_engine/common/util/pybind_helper.h
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/constants.py
  transformer_engine/pytorch/cpp_extensions/gemm.py
  transformer_engine/pytorch/csrc/common.cpp
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/comm_gemm_overlap.cpp
  transformer_engine/pytorch/csrc/extensions/gemm.cpp
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/extensions/quantizer.cpp
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/transformer.py
Labels: 2.0.0

#1455 [PyTorch] Remove MXFP8 scale-inv padding in MXFP8 all-gather
  transformer_engine/pytorch/distributed.py
Labels: bug, 2.0.0

#1449 [common] Generalized MXFP8 gated kernels w.r.t. input tensor dimensions
  tests/cpp/operator/test_cast_gated_swiglu.cu
  tests/cpp/operator/test_cast_mxfp8.cu
  tests/cpp/operator/test_cast_mxfp8_gated_swiglu.cu
  tests/cpp/test_common.cu
  tests/cpp/test_common.h
  transformer_engine/common/common.cu
  transformer_engine/common/common.h
  transformer_engine/common/transformer_engine.cpp
  transformer_engine/common/util/cast_gated_kernels.cuh
  transformer_engine/common/util/cast_kernels.cuh
  transformer_engine/common/util/dequantize_kernels.cuh
Labels: bug, testing, 2.0.0

#1457 Fix MXFP8 normalization
  transformer_engine/pytorch/csrc/extensions/normalization.cpp
Labels: 2.0.0

#1435 [PyTorch] Reduce tensor dimensions in MXFP8 tests
  tests/pytorch/distributed/run_numerics.py
  tests/pytorch/distributed/test_fusible_ops.py
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
Labels: bug, testing, 2.0.0

#1468 [MoE][PyTorch] Add prob permutation to mask-based MoE permutation; Fix FP8 related codes
  docs/api/pytorch.rst
  tests/pytorch/test_permutation.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/permutation.py
  transformer_engine/pytorch/triton/permutation.py
Labels: 2.1.0

#1485 [JAX] Flax with compute dtype inferred from input dtype.
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
  examples/jax/encoder/test_multiprocessing_encoder.py
  examples/jax/encoder/test_single_gpu_encoder.py
  examples/jax/mnist/test_single_gpu_mnist.py
  tests/jax/test_distributed_layernorm_mlp.py
  tests/jax/test_layer.py
  tests/jax/utils.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/flax/transformer.py
Labels: 2.1.0

#1495 [PyTorch] Fix typo
  transformer_engine/pytorch/distributed.py
Labels: bug, 2.1.0

#1488 [PyTorch] Fix fuse_wgrad_accumulation for GroupedLinear
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/module/grouped_linear.py
Labels: bug, 2.1.0

#1483 [PyTorch] Fix CP implementation with FP8
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/fp8.py
Labels: 2.1.0

#1466 [PyTorch] Use same API in optimizer `zero_grad` as PyTorch optimizers
  transformer_engine/pytorch/optimizers/fused_adam.py
  transformer_engine/pytorch/optimizers/fused_sgd.py
Labels: enhancement, 2.1.0

#1501 [PyTorch] Run all tests, even if one fails.
  qa/L0_pytorch_unittest/test.sh
  qa/L1_pytorch_distributed_unittest/test.sh
Labels: testing

#1504 Minor fixes for attention
  transformer_engine/common/fused_attn/fused_attn.cpp
  transformer_engine/pytorch/attention.py
Labels: 2.1.0

#1456 Parallel Cross Entropy using online softmax
  docs/api/pytorch.rst
  qa/L0_pytorch_unittest/test.sh
  setup.py
  tests/pytorch/test_parallel_cross_entropy.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/cross_entropy.py
  transformer_engine/pytorch/triton/cross_entropy.py
Labels: enhancement

#1507 Added memory alignment check to cast_fp8_1D
  transformer_engine/common/common.cu
  transformer_engine/common/common.h
  transformer_engine/common/util/cast_kernels.cuh
Labels: bug

#1508 [PyTorch] Skip context parallelism tests if not enough GPUs
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
Labels: bug, testing, 2.1.0

#1517 Update build test CUDA version to 12.1
  .github/workflows/build.yml
Labels: testing

#1515 Fix shape of new quantized tensor in `make_like`
  tests/pytorch/test_float8tensor.py
  transformer_engine/pytorch/tensor/float8_tensor.py
  transformer_engine/pytorch/tensor/quantized_tensor.py
Labels: bug

#1500 Delete extra tensor objects after restoring float8 tensors
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/tensor/_internal/float8_tensor_base.py
  transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
  transformer_engine/pytorch/tensor/float8_tensor.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
Labels: 2.1.0
