Repository NVIDIA/TransformerEngine, pull requests merged in 2025-05, with the labels that each got.

#1737 [JAX] Exclude GroupedGemm APIs for TE 2.3
  tests/jax/test_custom_call_compute.py
  transformer_engine/jax/cpp_extensions/gemm.py
  transformer_engine/jax/dense.py
Labels: 2.3.0

#1741 [PyTorch] Fix bug when reshaping norm output from LayerNormLinear
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
Labels: bug

#1742 [PyTorch] Debug UB conversion function from NVTEShape to std::vector
  transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
Labels: bug

#1752 Update README: Added GTC 2025 videos, latest news, and improved doc links
  README.rst
  docs/examples/comparison-fp8-bf16-training-nvidia-dgx-cloud-benchmarking-performance-explorer.jpg
Labels: 2.4.0

#1711 MXFP8 support in Userbuffers
  qa/L1_pytorch_distributed_unittest/test.sh
  tests/pytorch/distributed/run_gemm_with_overlap.py
  tests/pytorch/distributed/run_layer_with_overlap.py
  tests/pytorch/distributed/test_comm_gemm_overlap.py
  tests/pytorch/distributed/test_fusible_ops_with_userbuffers.py
  transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
  transformer_engine/common/util/logging.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/comm_gemm_overlap.cpp
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/module/_common.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/fused/userbuffers_backward_linear.py
  transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py
Labels: enhancement

#1758 [PyTorch] Avoid spurious warning with non-FP8 GroupedLinear
  transformer_engine/pytorch/module/grouped_linear.py
Labels: bug

#1754 [C][PyTorch]Make pytorch extensions pure cpp
  build_tools/pytorch.py
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/test_numerics.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/common.h
  transformer_engine/common/fused_attn/context_parallel.cu
  transformer_engine/common/fused_attn/flash_attn.cu
  transformer_engine/common/fused_attn/kv_cache.cu
  transformer_engine/common/fused_attn/utils.cu
  transformer_engine/common/include/transformer_engine/fused_attn.h
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/attention.cpp
  transformer_engine/pytorch/csrc/kv_cache.cuh
  transformer_engine/pytorch/csrc/thd_utils.cuh
Labels: 2.4.0

#1725 [PyTorch] Reduce verbosity of CI logs
  qa/L0_pytorch_unittest/test.sh
Labels: testing

#1790 Remove unused dependencies
  setup.py
Labels: testing

#1798 Fix README render for uploading package to PyPI
  README.rst
Labels: 2.4.0

#1799 Use an empty torch tensor to indicate no fp8 information in extra_state
  qa/L0_pytorch_unittest/test.sh
  setup.py
  tests/pytorch/test_hf_integration.py
  transformer_engine/pytorch/module/base.py
Labels: 2.4.0

#1611 [Pytorch] NVIDIA-DL-Framework-Inspect support – part 4 – documentation
  docs/debug.rst
  docs/debug/1_getting_started.rst
  docs/debug/2_config_file_structure.rst
  docs/debug/3_api_debug_setup.rst
  docs/debug/3_api_features.rst
  docs/debug/3_api_te_calls.rst
  docs/debug/4_distributed.rst
  docs/debug/api.rst
  docs/debug/img/api_calls1.svg
  docs/debug/img/api_calls2.svg
  docs/debug/img/fake_quant.svg
  docs/debug/img/introduction.svg
  docs/debug/img/names.svg
  docs/debug/img/pipeline_logging.svg
  docs/debug/img/reduction1.svg
  docs/debug/img/reduction2.svg
  docs/debug/img/reduction3.svg
  docs/debug/img/scaling_factors.svg
  docs/debug/img/tensorboard.png
  docs/index.rst
  qa/L0_pytorch_lint/test.sh
  transformer_engine/debug/features/per_tensor_scaling.py
Labels: 2.4.0

#1802 [PyTorch] Add docstring for CP load balancing
  transformer_engine/pytorch/attention/dot_product_attention/context_parallel.py
Labels: 2.4.0

#1803 Add missing docs for C API
  docs/api/c/cast_transpose_noop.rst
  docs/api/c/comm_gemm_overlap.rst
  docs/api/c/cudnn.rst
  docs/api/c/index.rst
  docs/api/c/multi_tensor.rst
  transformer_engine/common/include/transformer_engine/cast_transpose_noop.h
  transformer_engine/common/include/transformer_engine/fused_attn.h
  transformer_engine/common/include/transformer_engine/multi_tensor.h
Labels: documentation, 2.4.0

#1815 Remove `comm_gemm_overlap` doc
  docs/api/c/comm_gemm_overlap.rst
  docs/api/c/index.rst
Labels: 2.4.0

#1809 Build support for cuda 13
  build_tools/utils.py
  setup.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/common.cu
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/jax/setup.py
  transformer_engine/pytorch/setup.py
Labels: build

#1816 Add docs for missing FP8 recipes.
  docs/api/common.rst
  transformer_engine/common/recipe/__init__.py
Labels: 2.4.0

#1804 [PyTorch] Activation ops support fusing backward pass with quantize
  transformer_engine/pytorch/ops/basic/activation.py
Labels: enhancement
