Repository NVIDIA/TransformerEngine, pull requests merged in 2025-04, with the labels that each got.

#1636 Update list of authorized CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#1633 Fix fp8_buf for Linear and LayerNormLinear
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: 2.2.0

#1430 Introduce NVSHMEM based communication API for pytorch
  build_tools/pytorch.py
  setup.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/libtransformer_engine.version
  transformer_engine/common/nvshmem_api/CMakeLists.txt
  transformer_engine/common/nvshmem_api/nvshmem_waitkernel.cu
  transformer_engine/common/nvshmem_api/nvshmem_waitkernel.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/nvshmem_comm.cpp
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
Labels: 2.2.0

#1637 [PyTorch] Debug weight matrix usages for dgrad GEMM
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
Labels: bug

#1626 [PyTorch][Common] Refactor RoPE
  tests/pytorch/test_fused_rope.py
  transformer_engine/common/fused_rope/fused_rope.cu
  transformer_engine/common/include/transformer_engine/fused_rope.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/apply_rope.cpp
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/dot_product_attention/rope.py
Labels: 2.3.0

#1646 [PyTorch] Explicitly specify quantized tensor usages needed for linear op backward
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
Labels: bug

#1629 [PyTorch] Debug checkpointing with te.Sequential
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/ops/op.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
Labels: bug

#1665 [PyTorch] Add option in activation ops to cache input in FP8
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/ops/basic/activation.py
Labels: enhancement

#1676 [PyTorch] Avoid unnecessary tensor usages when caching for linear op backward
  transformer_engine/pytorch/ops/basic/basic_linear.py
Labels: bug

#1681 Fix #1524 and other softmax mask functionality
  tests/jax/test_layer.py
  tests/jax/test_softmax.py
  transformer_engine/jax/cpp_extensions/softmax.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/flax/transformer.py
Labels: bug, 2.3.0

#1694 [JAX] Deprecate Praxis layers
  qa/L2_jax_unittest/test.sh
  setup.py
  transformer_engine/jax/praxis/__init__.py
  transformer_engine/jax/praxis/module.py
  transformer_engine/jax/praxis/transformer.py
  transformer_engine/jax/setup.py
Labels: 2.3.0

#1703 Revert "Allow NVTEShape to own data."
  tests/cpp/test_common.cu
  tests/cpp/test_common.h
  transformer_engine/common/common.h
  transformer_engine/common/include/transformer_engine/transformer_engine.h
  transformer_engine/common/transformer_engine.cpp
  transformer_engine/pytorch/csrc/extensions/attention.cu
Labels: bug, 2.3.0

#1659 rtx5090 arch fix support
  tests/pytorch/test_float8tensor.py
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/common/include/transformer_engine/transformer_engine.h
  transformer_engine/common/transformer_engine.cpp
  transformer_engine/pytorch/csrc/extensions/quantizer.cpp
  transformer_engine/pytorch/csrc/extensions/util.cpp
  transformer_engine/pytorch/csrc/util.h
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/tensor/float8_tensor.py
  transformer_engine/pytorch/utils.py
Labels: 2.3.0

#1704 Refactor attention.py part 2
  docs/examples/attention/attention.ipynb
  docs/examples/te_llama/te_llama.py
  tests/pytorch/fused_attn/run_fused_attn_with_cp.py
  tests/pytorch/fused_attn/test_fused_attn.py
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
  tests/pytorch/fused_attn/test_kv_cache.py
  tests/pytorch/test_fused_optimizer.py
  tests/pytorch/test_fused_rope.py
  tests/pytorch/test_numerics.py
  transformer_engine/pytorch/__init__.py
  transformer_engine/pytorch/attention.py
  transformer_engine/pytorch/attention/__init__.py
  transformer_engine/pytorch/attention/dot_product_attention/__init__.py
  transformer_engine/pytorch/attention/dot_product_attention/backends.py
  transformer_engine/pytorch/attention/dot_product_attention/context_parallel.py
  transformer_engine/pytorch/attention/dot_product_attention/dot_product_attention.py
  transformer_engine/pytorch/attention/dot_product_attention/softmax.py
  transformer_engine/pytorch/attention/dot_product_attention/utils.py
  transformer_engine/pytorch/attention/inference.py
  transformer_engine/pytorch/attention/multi_head_attention.py
  transformer_engine/pytorch/attention/rope.py
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/graph.py
  transformer_engine/pytorch/transformer.py
  transformer_engine/pytorch/utils.py
Labels: 2.3.0

#1715 [PyTorch] Fix cuBLAS workspace leak in applications that initialize+destroy Userbuffers more than once
  transformer_engine/pytorch/module/base.py
Labels: bug, 2.3.0

#1727 [PyTorch] Check if FP8 block scaling is supported in tests
  tests/pytorch/distributed/test_cast_master_weights_to_fp8.py
Labels: bug

#1708 Kwyss/new shape owns data
  tests/cpp/operator/test_act.cu
  tests/cpp/operator/test_cast_dbias.cu
  tests/cpp/operator/test_cast_dbias_dgelu.cu
  tests/cpp/operator/test_cast_float8blockwise.cu
  tests/cpp/operator/test_cast_mxfp8.cu
  tests/cpp/operator/test_cast_mxfp8_gated_swiglu.cu
  tests/cpp/operator/test_cast_transpose.cu
  tests/cpp/operator/test_cast_transpose_current_scaling.cu
  tests/cpp/operator/test_cast_transpose_dbias.cu
  tests/cpp/operator/test_cast_transpose_dbias_dgelu.cu
  tests/cpp/operator/test_cast_transpose_dgeglu.cu
  tests/cpp/operator/test_causal_softmax.cu
  tests/cpp/operator/test_dequantize_mxfp8.cu
  tests/cpp/operator/test_multi_cast_transpose.cu
  tests/cpp/operator/test_multi_padding.cu
  tests/cpp/operator/test_normalization.cu
  tests/cpp/operator/test_normalization_mxfp8.cu
  tests/cpp/operator/test_qdq.cu
  tests/cpp/operator/test_transpose.cu
  tests/cpp/test_common.cu
  tests/cpp/test_common.h
  transformer_engine/common/comm_gemm_overlap/comm_gemm_overlap.cpp
  transformer_engine/common/common.h
  transformer_engine/common/include/transformer_engine/transformer_engine.h
  transformer_engine/common/transformer_engine.cpp
  transformer_engine/pytorch/csrc/extensions/attention.cu
  transformer_engine/pytorch/csrc/extensions/gemm.cpp
  transformer_engine/pytorch/csrc/extensions/permutation.cpp
  transformer_engine/pytorch/csrc/extensions/transpose.cpp
Labels: 2.4.0
