Repository NVIDIA/TransformerEngine, pull requests merged in 2025-07, with the labels that each got.

#1899 [PyTorch] Tests for loading previously-generated checkpoints
  .gitignore
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/test_checkpoint.py
  tests/pytorch/utils.py
Labels: testing

#1934 [PyTorch][MoE] MXFP8 Support to Reduce CPU Overhead By Fuse Torch Empty Calls
  benchmarks/linear/benchmark_grouped_linear.py
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions/cast.cpp
  transformer_engine/pytorch/csrc/quantizer.cpp
  transformer_engine/pytorch/tensor/_internal/mxfp8_tensor_base.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
Labels: performance

#1940 [JAX] Capped HuggingFace datasets version for TE/JAX encoder examples
  examples/jax/encoder/requirements.txt
  examples/jax/mnist/requirements.txt
Labels: bug, jax, 2.6.0

#1855 [JAX] GEMM custom op
  examples/jax/encoder/run_test_multiprocessing_encoder.sh
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
  examples/jax/encoder/test_multiprocessing_encoder.py
  tests/jax/test_custom_call_compute.py
  tests/jax/test_distributed_layernorm_mlp.py
  tests/jax/utils.py
  transformer_engine/jax/cpp_extensions/activation.py
  transformer_engine/jax/cpp_extensions/gemm.py
  transformer_engine/jax/cpp_extensions/misc.py
  transformer_engine/jax/cpp_extensions/normalization.py
  transformer_engine/jax/cpp_extensions/quantization.py
  transformer_engine/jax/csrc/extensions.h
  transformer_engine/jax/csrc/extensions/ffi.cpp
  transformer_engine/jax/csrc/extensions/gemm.cpp
  transformer_engine/jax/csrc/extensions/misc.h
  transformer_engine/jax/csrc/extensions/pybind.cpp
  transformer_engine/jax/dense.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/layernorm_dense.py
  transformer_engine/jax/layernorm_mlp.py
  transformer_engine/jax/quantize/dequantizer.py
  transformer_engine/jax/quantize/helper.py
  transformer_engine/jax/quantize/scaling_modes.py
  transformer_engine/jax/quantize/tensor.py
Labels: 2.6.0

#1938 Run-time checks for CUDA and cuBLAS versions
  transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
  transformer_engine/common/gemm/cublaslt_gemm.cu
  transformer_engine/common/util/cuda_runtime.cpp
  transformer_engine/common/util/cuda_runtime.h
  transformer_engine/common/util/rtc.cpp
Labels: bug, 2.6.0

#1949 Bump up FA to 2.8.1
  qa/L3_pytorch_FA_versions_test/test.sh
  transformer_engine/pytorch/attention/dot_product_attention/utils.py
Labels: 2.6.0

#1888 Handle dtypes more carefully in multi-tensor Adam
  transformer_engine/common/multi_tensor/adam.cu
  transformer_engine/common/multi_tensor/multi_tensor_apply.cuh
  transformer_engine/common/transformer_engine.cpp
Labels: bug, 2.6.0

#1955 [JAX] Tighten Encoder Test tolerances
  examples/jax/encoder/test_model_parallel_encoder.py
  examples/jax/encoder/test_multigpu_encoder.py
Labels: 2.6.0

#1954 [JAX] Remove unneccessary MXFP8 scale_inv padding
  tests/jax/test_distributed_layernorm.py
  transformer_engine/jax/cpp_extensions/gemm.py
  transformer_engine/jax/quantize/dequantizer.py
  transformer_engine/jax/quantize/tensor.py
Labels: 2.6.0

#1914 [Common] Optimize KV cache related kernels
  transformer_engine/common/fused_attn/kv_cache.cu
  transformer_engine/pytorch/attention/inference.py
Labels: 2.6.0

#1961 [PyTorch] Remove GH pinned deps
  build_tools/pytorch.py
  docs/debug/1_getting_started.rst
Labels: 2.6.0

#1965 Fix the condition error when checking fp8 attn in `get_attention_backend`
  transformer_engine/pytorch/attention/dot_product_attention/utils.py
Labels: 2.6.0

#1628 [Common] Improved performance of mxfp8 cast kernels
  tests/cpp/operator/test_cast_mxfp8.cu
  tests/cpp/operator/test_cast_mxfp8_gated_swiglu.cu
  tests/cpp/test_common.cu
  tests/cpp/test_common.h
  tests/jax/test_custom_call_compute.py
  transformer_engine/common/CMakeLists.txt
  transformer_engine/common/common.cu
  transformer_engine/common/common.h
  transformer_engine/common/util/cast_gated_kernels.cuh
  transformer_engine/common/util/cast_kernels.cuh
  transformer_engine/common/util/dequantize_kernels.cuh
  transformer_engine/common/util/ptx.cuh
  transformer_engine/common/utils.cuh
Labels: performance

#1974 Fix the device for cuDNN/cuBLAS handles
  qa/L1_pytorch_distributed_unittest/test.sh
  tests/pytorch/distributed/test_sanity.py
  transformer_engine/pytorch/attention/dot_product_attention/dot_product_attention.py
  transformer_engine/pytorch/module/grouped_linear.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
Labels: 2.6.0

#1990 [JAX] Fix current scaling test_helper.py and enable test_helper.py in L0
  qa/L0_jax_unittest/test.sh
  tests/jax/test_helper.py
Labels: 2.6.0

#1962 [JAX] Helper to disable TE custom calls + disable GemmPrimitive for non-MXFP8 recipes.
  qa/L0_jax_unittest/test.sh
  qa/L2_jax_unittest/test.sh
  tests/jax/test_custom_call_compute.py
  tests/jax/utils.py
  transformer_engine/jax/cpp_extensions/activation.py
  transformer_engine/jax/cpp_extensions/base.py
  transformer_engine/jax/cpp_extensions/quantization.py
  transformer_engine/jax/quantize/helper.py
Labels: 2.6.0

#1980 [JAX] Fixing GemmPrimitive partitioning rules to handle tensor-parallelism correctly for sequence-parallel inputs
  transformer_engine/jax/cpp_extensions/gemm.py
  transformer_engine/jax/dense.py
  transformer_engine/jax/flax/module.py
  transformer_engine/jax/flax/transformer.py
  transformer_engine/jax/layernorm_dense.py
  transformer_engine/jax/layernorm_mlp.py
  transformer_engine/jax/sharding.py
Labels: 2.6.0

#1999 [PyTorch] Prune L0 unit test
  qa/L0_pytorch_unittest/test.sh
  tests/pytorch/attention/test_attention.py
  tests/pytorch/test_cpu_offloading.py
  tests/pytorch/test_cuda_graphs.py
  tests/pytorch/test_fused_optimizer.py
  tests/pytorch/test_fused_router.py
  tests/pytorch/test_hf_integration.py
  tests/pytorch/test_numerics.py
  tests/pytorch/test_onnx_export.py
  tests/pytorch/test_parallel_cross_entropy.py
  tests/pytorch/test_sanity.py
Labels: testing

#2002 Fix the use-after-free bug in unfused normalization
  transformer_engine/pytorch/csrc/extensions/normalization.cpp
Labels: 2.6.0

#2008 [PyTorch] Fix bug with clearing op outputs during backward
  transformer_engine/pytorch/ops/fuser.py
Labels: bug
