Repository NVIDIA/TransformerEngine, pull requests merged in 2025-08, with the labels that each got.

#2044 [PyTorch] Update amax pointers when reallocating amax history in fusible ops
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/fuser.py
  transformer_engine/pytorch/ops/op.py
Labels: bug

#2017 [PyTorch] Fix bug when deducing dtype in linear functional API
  transformer_engine/pytorch/ops/basic/basic_linear.py
Labels: bug

#2063 [PyTorch] Avoid registering FP8 scale update in ops without backward pass
  transformer_engine/pytorch/ops/fuser.py
Labels: bug

#2007 [PyTorch] Disable fused dbias-quantize kernel for unsupported recipes
  tests/pytorch/test_fusible_ops.py
  transformer_engine/pytorch/csrc/extensions/bias.cpp
  transformer_engine/pytorch/csrc/extensions/cast.cpp
  transformer_engine/pytorch/ops/basic/bias.py
  transformer_engine/pytorch/ops/fused/backward_activation_bias.py
Labels: bug

#2050 [JAX] Trim dist fused attn tests in L1
  tests/jax/distributed_test_base.py
  tests/jax/test_distributed_fused_attn.py
Labels: 2.7.0

#2077 fix: fixes multi head attention for context parallel: rotary embedding to use padded cu_seq_lens
  transformer_engine/pytorch/attention/multi_head_attention.py
Labels: 2.7.0

#2088 [JAX] Error checking for mesh resource and update GemmPrimitive to use global_mesh_resource().fsdp_resource
  examples/jax/encoder/test_single_gpu_encoder.py
  examples/jax/mnist/test_single_gpu_mnist.py
  tests/jax/test_distributed_layernorm_mlp.py
  tests/jax/test_layer.py
  transformer_engine/jax/cpp_extensions/gemm.py
  transformer_engine/jax/quantize/helper.py
  transformer_engine/jax/sharding.py
Labels: 2.7.0

#2092 [PyTorch] Avoid garbage collection when capturing a CUDA Graph
  transformer_engine/pytorch/graph.py
Labels: bug, 2.7.0

#2081 Update list of authorized CI users
  .github/workflows/trigger-ci.yml
Labels: testing

#2090 [ TE-JAX ] Expose cp_strategy argument to DPA api
  transformer_engine/jax/flax/transformer.py
Labels: 2.7.0

#2121 Further relax constraints to cuDNN 9.13 for disabling fused attn for kv caching
  transformer_engine/pytorch/attention/dot_product_attention/utils.py
Labels: 2.7.0
