Repository NVIDIA/TransformerEngine, pull requests merged in 2025-06, with the labels that each got.

#1780 [PyTorch] Miscellaneous fixes for attention
  tests/pytorch/fused_attn/test_fused_attn.py
  transformer_engine/pytorch/attention/dot_product_attention/backends.py
  transformer_engine/pytorch/attention/dot_product_attention/utils.py
  transformer_engine/pytorch/attention/multi_head_attention.py
  transformer_engine/pytorch/transformer.py
Labels: 2.5.0

#1707 [PyTorch] FP8 Subchannel Recipe With FP8 Gather And Configurable Scaling Factor Tensor Swizzling
  tests/pytorch/distributed/run_numerics.py
  tests/pytorch/references/blockwise_quantizer_reference.py
  tests/pytorch/test_float8_blockwise_scaling_exact.py
  tests/pytorch/test_float8_current_scaling_exact.py
  tests/pytorch/test_float8blockwisetensor.py
  transformer_engine/common/common.h
  transformer_engine/common/include/transformer_engine/transformer_engine.h
  transformer_engine/common/transformer_engine.cpp
  transformer_engine/common/transpose/cast_transpose.h
  transformer_engine/common/transpose/quantize_transpose_vector_blockwise.cu
  transformer_engine/common/util/cast_kernels.cuh
  transformer_engine/common/util/pybind_helper.h
  transformer_engine/pytorch/cpp_extensions/gemm.py
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions/cast.cpp
  transformer_engine/pytorch/csrc/extensions/normalization.cpp
  transformer_engine/pytorch/csrc/quantizer.cpp
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/module/linear.py
  transformer_engine/pytorch/tensor/_internal/float8_blockwise_tensor_base.py
  transformer_engine/pytorch/tensor/float8_blockwise_tensor.py
Labels: enhancement, 2.5.0

#1812 [Common] Missing CUDA driver deallocations in Userbuffers
  transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers-host.cpp
  transformer_engine/common/comm_gemm_overlap/userbuffers/userbuffers.h
Labels: bug

#1862 Python 3.12+ support
  setup.py
Labels: 2.5.0

#1868 [PyTorch] Fix backward compatibility for checkpoint loading
  transformer_engine/pytorch/module/base.py
Labels: 2.5.0

#1847 [PyTorch] Inference mode disables initializing quantized weights with column-wise usage
  tests/pytorch/test_sanity.py
  transformer_engine/pytorch/module/base.py
  transformer_engine/pytorch/module/layernorm_linear.py
  transformer_engine/pytorch/module/layernorm_mlp.py
  transformer_engine/pytorch/tensor/mxfp8_tensor.py
Labels: bug, enhancement, 2.5.0

#1858 [PyTorch] Add support for FP8 current scaling in operation-based API
  tests/pytorch/distributed/test_fusible_ops.py
  tests/pytorch/distributed/test_fusible_ops_with_userbuffers.py
  tests/pytorch/test_fusible_ops.py
  tests/pytorch/utils.py
  transformer_engine/pytorch/distributed.py
  transformer_engine/pytorch/ops/basic/basic_linear.py
  transformer_engine/pytorch/ops/fused/userbuffers_forward_linear.py
Labels: enhancement, testing

#1851 [JAX] Add support for Fused Attn MLA head_dim_qk != head_dim_v
  tests/jax/test_distributed_fused_attn.py
  tests/jax/test_fused_attn.py
  transformer_engine/jax/attention.py
  transformer_engine/jax/cpp_extensions/attention.py
  transformer_engine/jax/csrc/extensions.h
  transformer_engine/jax/csrc/extensions/attention.cpp
  transformer_engine/jax/flax/transformer.py
Labels: 2.5.0

#1881 Fix test case that assumes char is signed
  tests/cpp/util/test_string.cpp
Labels: testing

#1793 [PyTorch][MoE] Reduce CPU Overhead By Fuse Torch Empty Calls
  benchmarks/linear/benchmark_grouped_linear.py
  transformer_engine/pytorch/csrc/common.h
  transformer_engine/pytorch/csrc/extensions.h
  transformer_engine/pytorch/csrc/extensions/cast.cpp
  transformer_engine/pytorch/csrc/extensions/pybind.cpp
  transformer_engine/pytorch/csrc/extensions/transpose.cpp
  transformer_engine/pytorch/csrc/quantizer.cpp
  transformer_engine/pytorch/module/grouped_linear.py
  transformer_engine/pytorch/tensor/_internal/float8_blockwise_tensor_base.py
  transformer_engine/pytorch/tensor/float8_blockwise_tensor.py
Labels: performance

#1896 Fix MLA CP Bugs
  tests/pytorch/fused_attn/run_fused_attn_with_cp.py
  tests/pytorch/fused_attn/test_fused_attn_with_cp.py
  transformer_engine/pytorch/attention/dot_product_attention/context_parallel.py
  transformer_engine/pytorch/attention/dot_product_attention/utils.py
Labels: 2.5.0
